tesseract-robotics/tesseract

tesseract_ros/src/kdl/kdl_env.cpp
=> Remove stray node handle

tesseract_collision/include/tesseract_collision/contact_checker_common.h
This corrects a build issue on my (somewhat) fresh system install.
=> Bullet Convex Hull Computer Include

tesseract_ros/include/tesseract_ros/kdl/kdl_env.h
=> Changed destruction order of plugin loader and instantiation of loaded class

tesseract_planning/CMakeLists.txt
Mirrors the changes made my moveit.
=> On Melodic, Fix Issue Where OMPL Package Is Not Found

tesseract_planning/include/tesseract_planning/basic_planner.h, tesseract_planning/include/tesseract_planning/trajopt/trajopt_planner.h, tesseract_planning/src/trajopt/trajopt_planner.cpp
I ran into the CMakeLists problem, but Reid had already fixed it here along with some other things.
=> Got TrajoptPlanner in working order

tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h, tesseract_collision/include/tesseract_collision/fcl/fcl_utils.h, tesseract_core/include/tesseract_core/basic_types.h
This appears to not fix the alignment issues, but perhaps it is a step in that direction.
=> Add EIGEN_MAKE_ALIGNED_OPERATOR_NEW macros

tesseract_core/include/tesseract_core/basic_types.h, tesseract_rviz/include/tesseract_rviz/render_tools/state_visualization.h
@Levi-Armstrong See associated Trajopt PR. Still does not fix my Eigen issues.
=> Eigen Alignment fixes

tesseract_ros/CMakeLists.txt, tesseract_ros/src/kdl/kdl_env.cpp, tesseract_ros/test/kdl_env_unit.cpp, tesseract_ros/test/urdf/lbr_iiwa_14_r820.srdf
The first commit introduces the test which results in a test failure. The second commit fixes the issue and the test now passes.
=> Add active link unit test

tesseract_ros/test/ros_tesseract_utils_unit.cpp
This is the benchmarking test I made to compare the new ACM method to the old one.
=> Add test to benchmark ACM isCollisionAllowed

tesseract/tesseract_support/cmake/tesseract_support-config.cmake.in
=> Don't set_and_check nonexistant tesseract_support include directory

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/types.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
=> Add succeeded waypoints and failed waypoints to PlannerResponse

.travis.yml, tesseract/tesseract_common/include/tesseract_common/status_code.h, tesseract/tesseract_environment/include/tesseract_environment/core/utils.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/planner.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_motion_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/hybrid/descartes_trajopt_array_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_array_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_freespace_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/src/hybrid/descartes_trajopt_array_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_array_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_freespace_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp
This PR adds functionality for printing collision information about a trajectory to the console. It also adds an additional optional boolean argument to the `solve` method of the motion planner base class about whether or not to print important motion planning information
=> Planner Verbosity

tesseract/tesseract_environment/include/tesseract_environment/core/environment.h, tesseract/tesseract_environment/include/tesseract_environment/core/state_solver.h, tesseract/tesseract_environment/include/tesseract_environment/kdl/kdl_state_solver.h, tesseract/tesseract_environment/src/core/environment.cpp, tesseract/tesseract_environment/src/kdl/kdl_state_solver.cpp
@schornakj I was able to track down the multi threaded issue thanks to the valgrind tool helgrind which quickly pointed out the issue. Could you test this?
=> Make tesseract environment thread safe

tesseract_ros/tesseract_rosutils/include/tesseract_rosutils/plotting.h
This adds the ability to plot cartesian waypoints to the ROS plotter. Eventually we could add plotters for joint waypoints (perhaps as a kinematic chain).
=> Add plotWaypoint

tesseract/tesseract_environment/include/tesseract_environment/core/utils.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/pose_samplers.h
The method for calculating the samples between -PI and PI should have been adding +1 to get the correct sampling count for a provided resolution.
=> Fix pose sampler

tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_approach_generator.h, tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_departure_generator.h
This PR adds two features to the axial approach/departure process generators
- Orientation interpolation for the input transform
- Removal of starting point duplicate
=> Axial Process Generator Update

tesseract/tesseract_common/package.xml
=> Add libclang-dev as a test_depend to tesseract_common

tesseract/tesseract/src/tesseract.cpp, tesseract/tesseract_kinematics/include/tesseract_kinematics/core/forward_kinematics_factory.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/core/inverse_kinematics_factory.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_fwd_kin_chain.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_fwd_kin_chain_factory.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_lma.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_lma_factory.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr_factory.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_utils.h, tesseract/tesseract_kinematics/src/kdl/kdl_fwd_kin_chain.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_lma.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_nr.cpp
This replaces #242 which has been rebased on master.
=> Add support for creating kinematic chain from multiple chains

tesseract/tesseract/src/tesseract.cpp, tesseract/tesseract_scene_graph/src/graph.cpp, tesseract/tesseract_scene_graph/test/tesseract_scene_graph_unit.cpp
I found these when testing out [DeepCode](https://www.deepcode.ai/). There are also a bunch of suggested changes in the Python code (mostly from PyLint), but I did not incorporate any of those.
=> Misc Code Quality Improvements

.github/workflows/main.yml
Adds a nightly CI run at midnight CST. I added this to [collaborative robotic sanding](https://github.com/swri-robotics/collaborative-robotic-sanding/blob/master/.github/workflows/main.yml), and it works fine there.
=> Daily cron job at midnight CST

.github/workflows/benchmarking.yml, tesseract/tesseract_collision/src/bullet/bullet_cast_bvh_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_cast_simple_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_discrete_bvh_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_discrete_simple_manager.cpp, tesseract/tesseract_collision/src/fcl/fcl_discrete_managers.cpp
=> Correctly overwrite collision objects with the same name

tesseract/tesseract_kinematics/include/tesseract_kinematics/ikfast/ikfast_inv_kin.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp
Move all implementation to the hpp.
=> Clean up ikfast_inv_kin

tesseract/tesseract_visualization/include/tesseract_visualization/visualization.h
A Joint Trajectory currently contains joint names and a TrajArray, but that will likely change soon.
=> Add plotting JointTrajectory to Visualization

tesseract/tesseract_visualization/CMakeLists.txt, tesseract/tesseract_visualization/cmake/tesseract_visualization-config.cmake.in, tesseract/tesseract_visualization/include/tesseract_visualization/visualization.h, tesseract/tesseract_visualization/include/tesseract_visualization/visualization_loader.h, tesseract/tesseract_visualization/package.xml, tesseract/tesseract_visualization/src/visualization_loader.cpp
We are in the process of releasing a visualization tool for tesseract which leverages Ignition. This tool will allow for dynamically loading a visualization class along with default constructor which looks for the library in the snap location.
=> Add visualization loader

tesseract/tesseract_environment/src/core/environment.cpp, tesseract/tesseract_scene_graph/include/tesseract_scene_graph/allowed_collision_matrix.h, tesseract/tesseract_scene_graph/include/tesseract_scene_graph/joint.h
Also adds some streaming operators that I added while trying to find it.
=> Fix bug in Environment::clone

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_planner_configurator.h, tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_planner_configurator.cpp
OMPL Documentation: https://ompl.kavrakilab.org/classompl_1_1geometric_1_1BiTRRT.html#a8f7bbe64f7b08b9c986f189339ceb2d1
MoveIt parameters (same defaults as OMPL): https://github.com/ros-planning/moveit/blob/7ad2bc7b86dad08061d98668ba34feba54bb05cc/moveit_setup_assistant/src/tools/moveit_config_data.cpp
=> Add BiTRRT Configurator

tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/iterative_spline_parameterization_process_generator.h, tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/iterative_spline_parameterization_process_generator.cpp
This should have been move instructions before.
=> Switch ISP to use MoveInstructions instead of PlanInstructions

tesseract/tesseract_environment/src/ofkt/ofkt_state_solver.cpp
OFKT has not been fully tested. However, clone now seems to work.
=> Fix OFKT clone method

.github/workflows/api_docs.yml
This should keep it from deleting the benchmark data.
=> Update api_docs.yml to keep benchmark files.

tesseract/tesseract_common/include/tesseract_common/utils.h, tesseract/tesseract_kinematics/include/tesseract_kinematics/core/validate.h, tesseract/tesseract_kinematics/src/core/rop_inverse_kinematics.cpp, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/utils/utils.h, tesseract/tesseract_planning/tesseract_command_language/src/utils/utils.cpp, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp, tesseract/tesseract_visualization/src/trajectory_interpolator.cpp
Also improves logging for the checkKinematics functions.
=> Fix descartes handeling of freespace plan types

tesseract/tesseract_common/include/tesseract_common/utils.h, tesseract/tesseract_planning/tesseract_process_managers/CMakeLists.txt, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/debug_observer.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_dt_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_waad_dt_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_waad_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/simple_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/src/debug_observer.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_dt_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_waad_dt_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_waad_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/simple_process_manager.cpp
This allow you enable debug with in a ProcessManager which will attache and observer which will output additional information as ti executes the taskfflow.
=> Add taskflow debug observer

tesseract/tesseract/include/tesseract/tesseract.h, tesseract/tesseract/src/tesseract.cpp, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp, tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp
This was added to support finding tcp when using ROS where it is only available via TF.
=> Add support for user defined find tcp callbacks

tesseract/tesseract/CMakeLists.txt, tesseract/tesseract/src/tesseract.cpp, tesseract/tesseract/test/CMakeLists.txt, tesseract/tesseract/test/benchmarks/CMakeLists.txt, tesseract/tesseract/test/benchmarks/tesseract_clone_benchmarks.cpp, tesseract/tesseract/test/tesseract_unit.cpp, tesseract/tesseract_environment/include/tesseract_environment/core/utils.h, tesseract/tesseract_environment/src/kdl/kdl_state_solver.cpp, tesseract/tesseract_environment/src/ofkt/ofkt_state_solver.cpp, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/utils.h, tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/continuous_contact_check_process_generator.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/discrete_contact_check_process_generator.cpp
A collection of misc fixes I have been meaning to push back.
=> Misc Fixes

tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/manipulator_info.h, tesseract/tesseract_planning/tesseract_command_language/test/utils_test.cpp
=> Add unit test for generateSkeletonSeed

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/planner_utils.h, tesseract/tesseract_planning/tesseract_process_managers/CMakeLists.txt, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/profile_switch_process_generator.h, tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/profile_switch_process_generator.cpp
This generator simply returns a value specified in the composite profile. This can be used to switch execution based on the profile
=> Add ProfileSwitchProcessGenerator

tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/fixed_size_assign_position.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/fixed_size_interpolation.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/lvs_interpolation.cpp, tesseract/tesseract_planning/tesseract_motion_planners/test/simple_planner_fixed_size_assign_position.cpp, tesseract/tesseract_planning/tesseract_motion_planners/test/simple_planner_fixed_size_interpolation.cpp, tesseract/tesseract_planning/tesseract_motion_planners/test/simple_planner_lvs_interpolation.cpp
This should fully address #410
=> Fix SimplePlanner step generators to correctly set profile

tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp, tesseract/tesseract_planning/tesseract_process_managers/CMakeLists.txt, tesseract/tesseract_planning/tesseract_process_managers/examples/raster_example_program.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_input.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_global_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_only_global_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/raster_only_process_manager.h, tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/motion_planner_process_generator.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_input.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_global_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_only_global_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/raster_only_process_manager.cpp, tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/freespace_taskflow.cpp, tesseract/tesseract_planning/tesseract_process_managers/test/tesseract_process_managers_unit.cpp
This PR breaks up the `RasterProcessManager `into two separate classes `RasterProcessManager` and `RasterGlobalProcessManager`. It also adds two additional raster process managers `(RasterOnlyProcessManager and RasterOnlyGlobalProcessManager)` which takes a program that does not include a from start and to home in the program. It also includes unit tests for the newly added managers.
=> Add raster only process managers

tesseract/tesseract_collision/examples/box_box_example.cpp, tesseract/tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h, tesseract/tesseract_collision/include/tesseract_collision/fcl/fcl_utils.h, tesseract/tesseract_collision/src/bullet/bullet_cast_bvh_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_cast_simple_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_discrete_bvh_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_discrete_simple_manager.cpp, tesseract/tesseract_collision/src/bullet/bullet_utils.cpp, tesseract/tesseract_collision/src/fcl/fcl_discrete_managers.cpp, tesseract/tesseract_collision/src/fcl/fcl_utils.cpp, tesseract/tesseract_collision/test/convex_concave_unit.cpp
@schornakj Maybe able to cherry-pick this commit to master.
=> Limit the use of new operator in tesseract_collision

tesseract/tesseract_environment/test/tesseract_environment_unit.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_fwd_kin_chain.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_fwd_kin_tree.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_lma.cpp, tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_nr.cpp
=> Clear KDL data in init

tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/command_language.h, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/instruction_type.h, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/timer_instruction.h, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/wait_instruction.h, tesseract/tesseract_planning/tesseract_command_language/src/deserialize.cpp, tesseract/tesseract_planning/tesseract_command_language/src/move_instruction.cpp, tesseract/tesseract_planning/tesseract_command_language/test/serialize_test.cpp
This PR adds a Wait and Timer Instructions similar to the ones on an industrial teach pendant.
=> Add wait and timer instruction to command language

tesseract/tesseract_common/include/tesseract_common/sfinae_utils.h, tesseract/tesseract_common/test/tesseract_common_unit.cpp, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/core/instruction.h, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/core/waypoint.h, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/joint_waypoint.h, tesseract/tesseract_planning/tesseract_command_language/src/state_waypoint.cpp, tesseract/tesseract_scene_graph/include/tesseract_scene_graph/srdf/group_opw_kinematics.h, tesseract/tesseract_scene_graph/test/tesseract_scene_graph_unit.cpp
This build on PR #452. Once merged this will be rebased.
=> This add SFINAE utils for checking if a class passed to template has a member function.

tesseract/tesseract_environment/include/tesseract_environment/ofkt/ofkt_nodes.h, tesseract/tesseract_environment/src/ofkt/ofkt_nodes.cpp, tesseract/tesseract_environment/src/ofkt/ofkt_state_solver.cpp
=> Remove limits from revolute nodes in OFKT state solver

tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_input.h, tesseract/tesseract_planning/tesseract_process_managers/src/process_input.cpp
Need to make it polymorphic so we can cast it back
=> Add virtual destructor to ProcessInfo

tesseract/tesseract/src/tesseract.cpp, tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/manipulator_info.h, tesseract/tesseract_planning/tesseract_command_language/src/manipulator_info.cpp, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/utils.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/problem_generators/default_problem_generator.h, tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h, tesseract/tesseract_planning/tesseract_motion_planners/src/core/utils.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/profile/trajopt_default_plan_profile.cpp, tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp, tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp
=> Add external tool center point support

tesseract/tesseract_kinematics/src/opw/opw_inv_kin.cpp, tesseract/tesseract_scene_graph/include/tesseract_scene_graph/graph.h, tesseract/tesseract_scene_graph/src/graph.cpp
Cherry pick commit from master to address issue #465
=> Make getShortestPath const

tesseract/tesseract_environment/include/tesseract_environment/core/commands.h, tesseract/tesseract_environment/include/tesseract_environment/core/state_solver.h, tesseract/tesseract_environment/include/tesseract_environment/kdl/kdl_state_solver.h, tesseract/tesseract_environment/include/tesseract_environment/ofkt/ofkt_state_solver.h, tesseract/tesseract_environment/src/kdl/kdl_state_solver.cpp, tesseract/tesseract_environment/src/ofkt/ofkt_state_solver.cpp
=> Update StateSolver to leverage KinematicLimits

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/robot_config.h
@Levi-Armstrong This is the feature implemented on the project machine.
=> Get Robot Redundancy

dependencies.rosinstall, dependencies_with_ext.rosinstall
=> Updated rosinstall to use specific versions for dependencies

tesseract_common/include/tesseract_common/utils.h, tesseract_kinematics/include/tesseract_kinematics/core/utils.h, tesseract_kinematics/test/kinematics_core_unit.cpp
This also includes an update to harmonize unit test in kinematics.
=> Add almost equal relative and abs vectorized version

tesseract_environment/include/tesseract_environment/core/environment.h
I had to read the code to make sure the things I documented here. I think this small addition could help others in the future and leave less space for guessing.
=> tesseract_environement: Improve documentation

tesseract_common/include/tesseract_common/timer.h
This is a supporting class used for timing examples and motion planning.
=> Add simple timer class

tesseract_common/include/tesseract_common/resource.h, tesseract_common/test/tesseract_common_unit.cpp
Here is the BytesResource test you requested.
=> Add tesseract_common::BytesResource unit test

tesseract_collision/include/tesseract_collision/core/common.h
This adds utility functions for scaling vertices about a point and about the center.
=> Add utility function to scale vertices about a point

dependencies.rosinstall, dependencies_with_ext.rosinstall, tesseract_kinematics/include/tesseract_kinematics/core/forward_kinematics.h, tesseract_kinematics/include/tesseract_kinematics/core/inverse_kinematics.h, tesseract_kinematics/include/tesseract_kinematics/core/rep_inverse_kinematics.h, tesseract_kinematics/include/tesseract_kinematics/core/rop_inverse_kinematics.h, tesseract_kinematics/include/tesseract_kinematics/core/utils.h, tesseract_kinematics/include/tesseract_kinematics/core/validate.h, tesseract_kinematics/include/tesseract_kinematics/ikfast/ikfast_inv_kin.h, tesseract_kinematics/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp, tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_fwd_kin_chain.h, tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_fwd_kin_tree.h, tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_lma.h, tesseract_kinematics/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr.h, tesseract_kinematics/include/tesseract_kinematics/opw/opw_inv_kin.h, tesseract_kinematics/src/core/rep_inverse_kinematics.cpp, tesseract_kinematics/src/core/rop_inverse_kinematics.cpp, tesseract_kinematics/src/kdl/kdl_fwd_kin_chain.cpp, tesseract_kinematics/src/kdl/kdl_fwd_kin_tree.cpp, tesseract_kinematics/src/kdl/kdl_inv_kin_chain_lma.cpp, tesseract_kinematics/src/kdl/kdl_inv_kin_chain_nr.cpp, tesseract_kinematics/src/opw/opw_inv_kin.cpp, tesseract_kinematics/test/kdl_kinematics_unit.cpp, tesseract_kinematics/test/kinematics_core_unit.cpp, tesseract_kinematics/test/kinematics_test_utils.h
This includes the following
- Update due to changes in opw kinematics
- Update inverse kinematics interface to return the solutions versus passing them in as out parameters.
=> Update kinematics interface

tesseract_visualization/include/tesseract_visualization/markers/toolpath_marker.h
=> Add scale to tool path marker

tesseract_common/CMakeLists.txt, tesseract_common/include/tesseract_common/kinematic_limits.h, tesseract_common/include/tesseract_common/types.h, tesseract_common/src/kinematic_limits.cpp, tesseract_common/test/tesseract_common_unit.cpp
This adds two utilities related to limits for checking if limits are within limits given an epsilon and another which force the provided position within the limits.
=> Add satisfy and enforce position limits utility functions

.github/workflows/bionic_build.yml, tesseract_collision/src/fcl/fcl_utils.cpp, tesseract_common/CMakeLists.txt, tesseract_common/include/tesseract_common/class_loader.h, tesseract_common/include/tesseract_common/class_loader.hpp, tesseract_common/include/tesseract_common/plugin_loader.h, tesseract_common/include/tesseract_common/plugin_loader.hpp, tesseract_common/test/CMakeLists.txt, tesseract_common/test/plugin_loader_unit.cpp, tesseract_common/test/test_plugin_base.h, tesseract_common/test/test_plugin_multiply.cpp, tesseract_common/test/test_plugin_multiply.h, tesseract_visualization/CMakeLists.txt, tesseract_visualization/cmake/tesseract_visualization-config.cmake.in, tesseract_visualization/include/tesseract_visualization/visualization_loader.h, tesseract_visualization/package.xml, tesseract_visualization/src/ignition/tesseract_ignition_visualization.cpp, tesseract_visualization/src/ignition/tesseract_ignition_visualization_plugin.cpp, tesseract_visualization/src/visualization_loader.cpp
This adds two classes to support loading plugins within Tesseract.
- Class ClassLoader: 
- This is a wrapper around Boost DLL for simplifying loading symbols from libraries.
- Class PluginLoader
- This leverages ClassLoader for loading plugins. This class supports adding search paths, multiple plugins, and Environment Variables to leverage for locating plugins. 
- This is what will be used throughout for managing plugins.
=> Remove dependency on class_loader and leverage Boost DLL

tesseract_collision/include/tesseract_collision/convex_decomposition/convex_decomposition_hacd.h, tesseract_collision/include/tesseract_collision/convex_decomposition/convex_decomposition_vhacd.h, tesseract_collision/src/convex_decomposition/convex_decomposition_hacd.cpp, tesseract_collision/src/convex_decomposition/convex_decomposition_vhacd.cpp
=> Fix Spelling of Convex Decomposition

tesseract_kinematics/src/core/rep_inverse_kinematics.cpp
=> remove duplication

tesseract_collision/bullet/src/bullet_factories.cpp, tesseract_collision/core/include/tesseract_collision/core/contact_managers_plugin_factory.h, tesseract_collision/core/src/contact_managers_plugin_factory.cpp, tesseract_collision/fcl/src/fcl_factories.cpp, tesseract_common/include/tesseract_common/class_loader.h, tesseract_common/include/tesseract_common/class_loader.hpp, tesseract_common/include/tesseract_common/plugin_loader.h, tesseract_common/include/tesseract_common/plugin_loader.hpp, tesseract_common/include/tesseract_common/types.h, tesseract_common/src/types.cpp, tesseract_common/test/plugin_loader_unit.cpp, tesseract_common/test/test_plugin_base.h, tesseract_common/test/test_plugin_multiply.cpp, tesseract_environment/include/tesseract_environment/commands/change_joint_acceleration_limits_command.h, tesseract_environment/include/tesseract_environment/commands/change_joint_position_limits_command.h, tesseract_environment/include/tesseract_environment/commands/change_joint_velocity_limits_command.h, tesseract_kinematics/core/include/tesseract_kinematics/core/kinematics_plugin_factory.h, tesseract_kinematics/core/src/kinematics_plugin_factory.cpp, tesseract_kinematics/core/src/rep_factory.cpp, tesseract_kinematics/core/src/rop_factory.cpp, tesseract_kinematics/kdl/src/kdl_factories.cpp, tesseract_kinematics/opw/src/opw_factory.cpp, tesseract_kinematics/ur/src/ur_factory.cpp, tesseract_visualization/include/tesseract_visualization/visualization.h, tesseract_visualization/src/ignition/tesseract_ignition_visualization.cpp
=> Updated plugin capability to support sections

.run-cpack, tesseract_collision/CMakeLists.txt, tesseract_common/CMakeLists.txt, tesseract_environment/CMakeLists.txt, tesseract_geometry/CMakeLists.txt, tesseract_kinematics/CMakeLists.txt, tesseract_scene_graph/CMakeLists.txt, tesseract_srdf/CMakeLists.txt, tesseract_state_solver/CMakeLists.txt, tesseract_urdf/CMakeLists.txt, tesseract_visualization/CMakeLists.txt
Updates to CPack to get correct binary builds. I've tested this on Ubuntu Focal but haven't had a chance to test with Windows yet.
=> CPack Updates

tesseract_common/include/tesseract_common/type_erasure.h
The WIN32 API defines `instance` and a few other names that are used in type_erasure.h. Rename these symbols to avoid this problem.
=> Renames in type erasure to avoid WIN32 defines

.github/workflows/windows_2019.yml, tesseract_support/test/tesseract_support_unit.cpp
This PR fixes the Windows 2019 github action build failures.
=> Fix the Windows 2019 github action

tesseract_environment/CMakeLists.txt
=> Add forgotten source file extension to CMakeLists.

.github/workflows/benchmarking.yml
Update per commit message. Addresses #854
=> Benchmark CI Job Update

.github/workflows/benchmarking.yml, .github/workflows/code_quality.yml, .github/workflows/nightly.yml, .github/workflows/ubuntu.yml
=> Use tesseract organization fork of ICI

.github/workflows/code_quality.yml
=> Updated code coverage job

tesseract_environment/test/benchmarks/CMakeLists.txt, tesseract_environment/test/benchmarks/check_trajectory_benchmarks.cpp
Finally getting around to benchmarking the collision checking for #765
=> implemented benchmarking for checking trajectories

tesseract_common/src/resource_locator.cpp
=> Fix resource locator error message 

tesseract_collision/fcl/src/fcl_utils.cpp
=> Remove invalid assert from FCL collision and distance callback functions

.github/workflows/add_ros_apt_sources.sh, .github/workflows/ubuntu.yml
Changes per commit message; replaces #905
=> Add Jammy CI Build

tesseract_kinematics/core/src/kinematics_plugin_factory.cpp
=> Improved reporting of errors in IK plugin loader

.github/workflows/conda.yml, .github/workflows/conda/recipe/bld.bat, .github/workflows/conda/recipe/meta.yaml
This PR fixes the conda ci tests.
=> Fix conda tests

tesseract_collision/core/include/tesseract_collision/core/types.h
=> Fix map type in comment of ContactResultMap

tesseract_common/src/utils.cpp
=> Handle edge case in calcJacobianTransformErrorDiff

tesseract_environment/src/environment.cpp
=> Only run kinematic check when testing is enabled and debug is enabled

tesseract_kinematics/core/include/tesseract_kinematics/core/kinematic_group.h, tesseract_kinematics/core/src/kinematic_group.cpp
=> Expose Inverse Kinematics in Kinematics Group
