tesseract-robotics/tesseract

tesseract_collision/src/bullet/bullet_utils.cpp
tesseract_collision/src/fcl/fcl_utils.cpp
tesseract_core/include/tesseract_core/basic_types.h
tesseract_monitoring/CMakeLists.txt
tesseract_monitoring/launch/contact_monitor.launch
tesseract_monitoring/src/contact_monitor.cpp
tesseract_msgs/msg/ContactResult.msg
tesseract_ros/include/tesseract_ros/ros_tesseract_utils.h

Also fixes failing asserts which should have been not equals.
This also adds a timestamp to the contact results message.

Update contact monitor to use the latest version

---

tesseract_planning/CMakeLists.txt
tesseract_planning/src/ompl/chain_ompl_interface.cpp

Fixups required to use the OMPL planner effectively with other ROS systems. This includes
* a change to compute the transforms and set the transforms of the whole scene, and  
* a fix to the CMakeLists to export the right libraries.

OMPL Planner Fixups

---

tesseract_planning/src/trajopt/trajopt_planner.cpp

Adds in the two lines so that the final collision check actually works

Fix trajopt planner collision check

---

tesseract_monitoring/src/contact_monitor.cpp
tesseract_msgs/msg/ContactResultVector.msg

The array field in ContactResultVector.msg has a typo "constacts."

Fixed typo 'constacts' in ContactResultVector.msg

---

tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h
tesseract_collision/src/bullet/bullet_utils.cpp
tesseract_core/include/tesseract_core/basic_types.h
tesseract_planning/include/tesseract_planning/trajopt/trajopt_planner.h
tesseract_planning/src/trajopt/trajopt_planner.cpp
tesseract_ros/include/tesseract_ros/ros_basic_plotting.h
tesseract_ros/include/tesseract_ros/ros_tesseract_utils.h
tesseract_rviz/include/tesseract_rviz/tesseract_state_plugin/tesseract_state_display.h
tesseract_rviz/src/tesseract_state_plugin/tesseract_state_display.cpp

* The first commit ignore warning messages in bullet
* The second commit simplifies the trajopt planner by introducing a TrajOptPlannerConfig structure which reduces the number of overload methods.
* The third adds joint_state monitoring to the state display so the state in rviz gets updated if joint_states changes.
* The forth commit fixes an error in the axis plotting and also add utils for converting tesseract informtiaon to JointStateMsg's

Cleanup and Simplify a few things

---

tesseract_collision/CMakeLists.txt
tesseract_collision/test/collision_large_dataset_unit.cpp
tesseract_collision/test/collision_multi_threaded_unit.cpp
tesseract_monitoring/CMakeLists.txt
tesseract_planning/CMakeLists.txt
tesseract_ros/CMakeLists.txt
tesseract_rviz/CMakeLists.txt

For some reason i was recieving several warnings from within gtest and the ignore warning was not solving the issue. In order to resolve the warnings was to using the `target_compiler_options` instead of `add_compiler_options`.

Fix warnings in unit tests

---

tesseract_monitoring/include/tesseract_monitoring/environment_monitor.h
tesseract_monitoring/src/environment_monitor.cpp
tesseract_ros/include/tesseract_ros/ros_tesseract_utils.h

This PR adds a service interface to the environment monitor for modifying the environment, and implements the `MOVE` enumeration in the tesseract state message conversion utility

Environment Interface Improvements

---

tesseract_planning/CMakeLists.txt
tesseract_planning/include/tesseract_planning/trajopt/trajopt_array_planner.h
tesseract_planning/include/tesseract_planning/trajopt/trajopt_freespace_planner.h
tesseract_planning/include/tesseract_planning/trajopt/trajopt_planner.h
tesseract_planning/include/tesseract_planning/waypoint_definitions.h
tesseract_planning/src/trajopt/trajopt_array_planner.cpp
tesseract_planning/src/trajopt/trajopt_freespace_planner.cpp

I imagine we will want to revisit these at some point when we figure out exactly what we want this API to look like, but they do work. They solve the immediate need of an easier way to use Trajopt.
This adds a freespace planner and an array planner. The freespace planner plans between a start and end position with some number of steps. The array planner plans along a given list of poses (e.g. like you might find in a ROS PoseArray msg). Both of them generate the TrajOpt problem and solve it internally based on the information in the config file. I also add the Waypoint base class along with cartesian_waypoint and joint_waypoint. Again, we may want to revisit exactly what is in those at a later date.
To test, you can use my example here …

Add TrajOpt Freespace and Array Planners

---

tesseract_planning/include/tesseract_planning/trajopt/trajopt_array_planner.h
tesseract_planning/include/tesseract_planning/trajopt/trajopt_freespace_planner.h
tesseract_planning/include/tesseract_planning/waypoint_definitions.h
tesseract_planning/src/trajopt/trajopt_array_planner.cpp
tesseract_planning/src/trajopt/trajopt_freespace_planner.cpp

Adds some desired functions to the array and freespace planners. These correspond to the commits. They should be more or less independent of each other.
- Ability to pass coeffs through for each waypoing
- Ability to declare a waypoint a cost or constraint (note: Naming of this could change)
- Add a toleranced joint waypoint  (No cartesian mostly b/c its not in trajopt yet)
- Add desired configuration parameter - This is a joint cost applied to all of the points in the trajectory to pull it toward a desired configuration. Motivation was a desire to pull the trajectory away from singularities
- Fixed clang warnings

Tesseract planner improvements

---

tesseract_planning/include/tesseract_planning/trajopt/trajopt_planner.h
tesseract_planning/src/trajopt/trajopt_planner.cpp

The tesseract planner interface expects all error codes to be less than one. Trajopt returns all positive status codes so this fixes the tesseract to return errors from TrajOpt with the correct tesseract planner interface error codes.

Fix trajopt planner to return correct status

---

tesseract_planning/include/tesseract_planning/utils.h

It uses the coeffs and is_critical from the starting waypoint. This was a fairly arbitrary choice.

Add passthrough for coeffs when interpolating waypoints

---

tesseract/tesseract_collision/test/collision_box_box_unit.cpp
tesseract/tesseract_collision/test/collision_box_sphere_unit.cpp
tesseract/tesseract_collision/test/collision_large_dataset_unit.cpp
tesseract/tesseract_collision/test/collision_multi_threaded_unit.cpp
tesseract/tesseract_collision/test/collision_octomap_sphere_unit.cpp
tesseract/tesseract_collision/test/collision_sphere_sphere_unit.cpp

This enables FCL tests, but one test still fails. I have confirmed in blender that Bullet produces the correct results and FCL does not. Need to create an issue on FCL.

Enable FCL tests since PR #338 was merged

---

tesseract/tesseract_scene_graph/include/tesseract_scene_graph/parser/urdf_parser.h

Fix for #114
Does changing this flag break anything else?

Avoid flattening collision meshes when parsing URDFs

---

tesseract_ext/bullet3_ros/package.xml
tesseract_ext/fcl_ros/package.xml
tesseract_ext/libccd_ros/package.xml

No longer needed since these are ROS-agnostic packages.

Remove catkin buildtool dependencies from tesseract_ext packages

---

tesseract/tesseract_environment/src/core/environment.cpp

When the environment is created through the `tesseract` pointer, contact managers are initialized after the environment is created, and the initial world transforms for all collision objects don't get set correctly. This PR fixes this issue by calling the `currentStateChanged` method after setting an active contact manager to set the initial transforms of all collision objects.

Update current state

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_tesseract_kinematics.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_tesseract_kinematics.hpp
tesseract/tesseract_planning/tesseract_motion_planners/test/CMakeLists.txt
tesseract/tesseract_planning/tesseract_motion_planners/test/descartes_tesseract_kinematics_tests.cpp

This adds a wrapper for a TesseractKinematics object such that it can be used with Descartes. It has currently only been tested with the default KDL kinematics, but ideally it would eventually provide an interface for any of Tesseract's kinematics solvers to be used with descartes.

Add DescartesTesseractKinematics wrapper

---

tesseract_ros/tesseract_monitoring/src/environment_monitor.cpp
tesseract_ros/tesseract_msgs/srv/GetEnvironmentInformation.srv
tesseract_ros/tesseract_rosutils/include/tesseract_rosutils/utils.h

The GetEnvironmentInformation service uses the bitwise AND operator to separate user requests and send only certain information.  However, there are two things that seem incorrect.
- the 'flag' for ALLOWED_COLLISION_MATRIX was 254.  254 converts to 1111 1110.  Requesting this matrix was identical to requesting everything from LINK_LIST through JOINT_TRANSFORM.  Therefore, all of those would return if the ACM was requested, and the ACM would return if any of those were requested.
- the 'flag' for COMMAND_HISTORY was 0.  0 converts to 0000 0000.  Since bitwise AND between any number and 0 is 0 (which C++ translates as false), COMMAND_HISTORY was never returned.
In order to fix this:
- Changed from 8-bit ints to 16-bit ints (needed the room, since there are 10 items to 'flag')
- Incremented …

Modifying Flags in GetEnvironmentInformation.srv

---

tesseract/tesseract_collision/CMakeLists.txt

This is part of a workaround for an issue in ROS2 pluginlib (https://github.com/ros/pluginlib/issues/161). Briefly, the ROS2 implementation of ClassLoader uses `ament_index_cpp::get_package_prefix()` when loading plugins, which makes it difficult to load plugins from non-ROS libraries since they aren't added to the `AMENT_PREFIX_PATH` environment variable and don't have some ROS2-specific config files in their package `share` directory.
This change solves the second of these problems by writing an empty file to `ros2_ws/install/tesseract_collision/share/ament_index/resource_index/packages/tesseract_collision` when the package is built.
I think that the first problem will need to be handled separately. So far I've been adding the path to the installed location of `tesseract_collision` to …

Allow tesseract_collision plugins to be found by ROS2 packages

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/waypoint.h
tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_approach_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_departure_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/passthrough_process_generator.h
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/basic_cartesian_plan.json
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/glass_up_right_plan.json

This PR updates the waypoint definitions:
-  Cartesian: adds string for link to which the waypoint transform is relative
- JointToleranced: inherits from the Joint waypoint
Corresponds to `trajopt_ros` PR [130](https://github.com/ros-industrial-consortium/trajopt_ros/pull/130)

Waypoint Definition Update

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp

I don't think this header is used for anything in this file, and it causes build failures under ROS2.

Remove unused ROS1 header from Descartes motion planner impl

---

tesseract/tesseract_urdf/src/urdf_parser.cpp

The `urdf_parser.cpp` file was checking for duplicate joint names using the getLink() function instead of getJoint(). This is incorrect since joints and links can have the same name in URDF.

Fix check for duplicate joints in urdf_parser.cpp

---

tesseract_ros/tesseract_rosutils/include/tesseract_rosutils/plotting.h

The getMarkerCylinderMsg function was setting the header frame id to the name of the urdf when it should be set to the root link name of the urdf.

Fix getMarkerCylinderMsg header frame id

---

tesseract_ros/tesseract_rviz/src/render_tools/environment_widget.cpp

I was playing with the RViz visualizer, and noticed a crash when trying to remove a joint from the environment. I had two errors pop up:
- `The link () does not exist`: caused by trying to remove `remove_link` which is not set as this is a `REMOVE_JOINT` command
- `The link (child_link_name) does not exist`: Caused by removing the link before the joint. When the link is removed, the widget is updated, and walks the list of joints. When it hits the joint to be removed, the child link no longer exists and crashes.
This PR thus removes the joint, then the child link (instead of `remove_link`).
As a side note, it seems like travis supports `xvfb`, so it might be possible to run tests against RViz in CI, but it doesn't seem that easy to set up.

Fix removing joint in RViz

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp

When passed by reference, calling clear on the planner also clears the config that was passed in. If it is by value, you will just be setting the planners config to nullptr not the original.

Trajopt Planner: Switch setConfiguration to pass shared_ptr by value

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/impl/ompl_freespace_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_freespace_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_settings.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_freespace_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_planner_tests.cpp

This PR updates the OMPL planner to simplify configuration; it also refactors the unit test to be able to test all types of OMPL planners. I wasn't able to get the RRT* planner to converge in the unit test scenario, but all of the other planners work. The refactor of the OMPL planner part of an effort to create a hybrid OMPL planner that is still in progress

OMPL Planner Simplification

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/waypoint.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/impl/ompl_freespace_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_freespace_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/utils.cpp

Since joint waypoint order is not guaranteed to match the manipulator the planners must adjust the waypoint data to match the manipulator.

Adjust for joint waypoint joint name order

---

tesseract/tesseract_environment/src/core/environment.cpp
tesseract/tesseract_environment/test/tesseract_environment_unit.cpp

This is to avoid potential deadlock when returning early
e.g. when deleting a non-existing link.
Currently, if any of the calls to `Environment` that's mutex-protected and can fail does fail, the mutex is left locked, and any subsequent calls will fail.
Also updated the test to check double-removing, maybe it should be done for other functions as well.

Replace raw lock / unlock by lock_guard

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision.hpp

Add a parameter to the constructor of `tesseract_motion_planners::DescartesCollision` that sets the contact distance threshold of its underlying `DiscreteContactManager`. This is useful if you want Descartes to provide a seed trajectory that leaves a buffer vs. collision geometry near the process waypoints, since I think the distance threshold defaults to 0.0 m otherwise.

Expose the contact distance threshold for DescartesCollision

---

tesseract/tesseract_environment/include/tesseract_environment/core/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/CMakeLists.txt
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision_edge_evaluator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision_edge_evaluator.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/impl/ompl_freespace_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/src/descartes/descartes_collision_edge_evaluator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/descartes_planner_tests.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/basic_cartesian_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/car_seat_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/glass_up_right_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_auxillary_axes_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_example.cpp
tesseract_ros/tesseract_rviz/src/render_tools/manipulation_widget.cpp

This PR includes:
- Fixed manipulation widget to handle continuous joints
- Update checkTrajectory and supporting function to leverage state solver and contact test type
- Add a descartes collision edge evaluator

Add descartes collision edge eval, Fix manipulation widget

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision_edge_evaluator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision_edge_evaluator.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/continuous_motion_validator.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/continuous_motion_validator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_trajopt_planner_test.cpp

The environment is thread safe but the state solver and contact managers are not so they must be cloned for each thread that is being used.

Use state solver in descartes edge evaluator and ompl motion validator

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/trajopt_planner_default_config.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp

This PR updates the TrajOpt Default Configuration class with a boolean and coefficient value for using the new TrajOpt avoid singularity cost

TrajOpt Config Update: Avoid Singularity 

---

tesseract/tesseract_collision/CMakeLists.txt
tesseract/tesseract_collision/cmake/tesseract_collision-config.cmake.in

As FCL doesn't do it in their config file, we need to do it ourselves
This would fix #191 , but is suboptimal as FCL actually uses a more complex logic to fallback on pkg-config if they can't find the CMake package.

Explictly look for libccd

---

.travis.yml
tesseract/tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h
tesseract/tesseract_collision/src/bullet/bullet_utils.cpp
tesseract/tesseract_collision/test/collision_sphere_sphere_cast_unit.cpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/continuous_motion_validator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/impl/ompl_freespace_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_freespace_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/trajopt_planner_default_config.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/continuous_motion_validator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_freespace_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_trajopt_planner_test.cpp
tesseract_python/tesseract_python/CMakeLists.txt
tesseract_python/tesseract_python/cmake/FindSWIG.cmake
tesseract_python/tesseract_python/swig/tesseract_planning/tesseract_motion_planners/trajopt/config/trajopt_planner_config.i
tesseract_python/tesseract_python/swig/tesseract_planning/tesseract_motion_planners/trajopt/config/trajopt_planner_default_config.i
tesseract_python/tesseract_python/swig/trajopt/problem_description.i
tesseract_python/tesseract_python/tests/test_trajopt_motion_planner.py
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/basic_cartesian_plan.json
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/glass_up_right_plan.json
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/basic_cartesian_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/car_seat_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/glass_up_right_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/pick_and_place_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_auxillary_axes_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_example.cpp
tesseract_ros/tesseract_rviz/include/tesseract_rviz/render_tools/link_widget.h
tesseract_ros/tesseract_rviz/src/render_tools/link_widget.cpp

This add ability to handle fixed states throughout the provided trajectory for collision. It also simplifies the trajopt configs to reduce code duplication. 
Update:
Noticed that there is an intermittent bug in OMPL hybridization which will return a plan that starts at the end and finishes at the end. Need to create issue on OMPL. 
Updated tesseract to support bullet being built using double precision.
Update rviz link_widget to support tesseract octree sub shape type SPHERE_INSIDE and SPHERE_OUTSIDE visualization.

Update trajopt planner handling of fixed start and end states for collision

---

.travis.yml
tesseract/tesseract_collision/CMakeLists.txt

Supports [this `tesseract_ext` issue](https://github.com/ros-industrial-consortium/tesseract_ext/issues/10) and [this PR](https://github.com/ros-industrial-consortium/tesseract_ext/pull/11). Workaround for [a bullet3 issue](https://github.com/bulletphysics/bullet3/issues/2582) where it doesn't correctly export some compiler definitions.

Add double precision flag to tesseract_collision target compile definitions

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/trajopt_collision_config.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/trajopt_planner_default_config.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_freespace_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_trajopt_planner_test.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp
tesseract_python/tesseract_python/swig/tesseract_planning/tesseract_motion_planners/trajopt/config/trajopt_collision_config.i
tesseract_python/tesseract_python/swig/tesseract_planning/tesseract_motion_planners/trajopt/config/trajopt_planner_default_config.i

Add separate collisions terms for constraint and cost and expose them in the TrajOpt planner configs. It's important for collisions to be represented as constraints to ensure that the resulting trajectory is collision-free. In certain cases it is desirable for collisions to also be modeled as costs to drive the solution further away from nearby collisions if possible.
- Add new functions to allow adding collision terms as either costs or constraints.
- ~~Added new parameters in the TrajOpt planner configs to set if collisions will be disabled, modeled as constraints, or modeled as both costs and constraints.~~
- ~~If collisions are enabled they will be modeled as constraints. If `collision_check = true`, a collision constraint term will be added with a safety margin of …

Allow adding TrajOpt collision terms as both constraints and costs

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/impl/ompl_motion_planner.hpp

The ompl solve call when optimize config param set to true had an issue so it was not disabling hybridization.

Fix missed disabling ompl planner hybirdization when config param optimize set to true

---

tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_auxillary_axes_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/puzzle_piece_example.cpp

When the default solver was switched to OSQP the test takes longer to run causing the test to fail. I set the two puzzle piece test to use the BMPD solver which solve the issue.

Use BMPD solver for puzzle piece examples

---

tesseract_python/tesseract_python/swig/tesseract/tesseract.i
tesseract_python/tesseract_python/swig/tesseract_python.i
tesseract_python/tesseract_python/swig/tesseract_scene_graph/srdf_parser.i
tesseract_python/tesseract_python/tests/test_srdf_parser.py

This commit adds a new binding for srdf_parser.h
Current support is:
- Retrieving Groups and GroupStates
- Accessing their members
Note that due to SWIG's lack of support of nested classes, they end up
flattened, at the root of the module.
This PR still lacks a few things, namely tests but I'd like to get a few comments on this code first.

Add initial support for Groups and GroupStates

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/trajopt_collision_config.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/config/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/utils.cpp
tesseract_python/tesseract_python/swig/tesseract_planning/tesseract_motion_planners/trajopt/config/trajopt_collision_config.i

Depends on #210, as well as [#160 in `trajopt_ros`](https://github.com/ros-industrial-consortium/trajopt_ros/pull/160). ~~Should be rebased after #210 is merged.~~
Exposes the new `safety_margin_buffer` parameter, which helps keep the optimization away from collisions when the safety margin distance is very small.

Use Trajopt safety_margin_buffer parameter

---

tesseract/tesseract_environment/include/tesseract_environment/core/environment.h
tesseract/tesseract_environment/src/core/environment.cpp
tesseract/tesseract_environment/test/tesseract_environment_unit.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_planner_tests.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_trajopt_planner_test.cpp
tesseract/tesseract_scene_graph/examples/build_scene_graph_example.cpp
tesseract/tesseract_scene_graph/examples/parse_srdf_example.cpp
tesseract/tesseract_scene_graph/include/tesseract_scene_graph/graph.h
tesseract/tesseract_scene_graph/include/tesseract_scene_graph/joint.h
tesseract/tesseract_scene_graph/include/tesseract_scene_graph/link.h
tesseract/tesseract_scene_graph/src/graph.cpp
tesseract/tesseract_scene_graph/test/tesseract_scene_graph_unit.cpp
tesseract/tesseract_urdf/src/urdf_parser.cpp
tesseract_python/tesseract_python/swig/ros/tesseract_rosutils/utils.i
tesseract_python/tesseract_python/swig/tesseract_environment/core/environment.i
tesseract_python/tesseract_python/swig/tesseract_scene_graph/graph.i
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/basic_cartesian_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/car_seat_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/glass_up_right_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/pick_and_place_example.cpp
tesseract_ros/tesseract_rosutils/include/tesseract_rosutils/utils.h
tesseract_ros/tesseract_rviz/src/render_tools/environment_widget.cpp

This is a proposal to fix #142 
Basically introduce a new API to add a SceneGraph to another one, possibly with a prefix. This allows to `parseURDF` once, and add the same robot to the same scene multiple times with different names. Unfortunately, I needed to create prefixed copy operators for links and joints. As long as `name_` is a `const` member, I couldn't figure out a very good way to write them any other way.
The copying itself is done as breadth-first search over all links / joints, copying it into a prefixed version and adding to current Environment.
I also created a test that demonstrates usage and checks the following:
- Adding an empty scene graph always succeeds (nothing to do)
- Adding multiple times the same scene graph fails without prefix, succeeds with it

Allow to merge a SceneGraph into another one

---

tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp

Allows the use of JOINT_INTERPOLATED in Trajopt_planner.
Only add waypoints to the fixed_waypoint list if they are critical. Currently it treats any joint position waypoint as fixed which may not be the case depending on the coefficient

Planner fixes

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/hybrid/descartes_trajopt_array_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/test/descartes_tesseract_kinematics_tests.cpp
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_approach_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/axial_departure_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/extension_departure_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/linear_transition_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/passthrough_process_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/generators/passthrough_transition_generator.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/process_definition.h
tesseract/tesseract_planning/tesseract_process_planners/include/tesseract_process_planners/process_planner.h
tesseract/tesseract_planning/tesseract_process_planners/src/tesseract_process_planners/process_definition.cpp
tesseract/tesseract_planning/tesseract_process_planners/test/custom_iterator_unit.cpp
tesseract/tesseract_planning/tesseract_process_planners/test/tesseract_process_planners_unit.cpp

If a path has all poses in all raster strokes with x and y pointing in the same direction (not flipping back and forth each stroke), a departure with x/y components will 'backtrack' on some strokes and continue 'forward' on others.  This commit changes that so that 'positive' x/y values always move away from the penultimate pose in a stroke, and 'negative' x/y values always move back towards the penultimate pose in a stroke.
If the general method used is agreeable, I could add a second commit doing the same for the axial approach generator.

Adjust Departure Generator

---

tesseract_ros/tesseract_examples/tesseract_ros_examples/CMakeLists.txt
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/examples.rviz
tesseract_ros/tesseract_examples/tesseract_ros_examples/config/scene_graph_example.srdf
tesseract_ros/tesseract_examples/tesseract_ros_examples/include/tesseract_ros_examples/scene_graph_example.h
tesseract_ros/tesseract_examples/tesseract_ros_examples/launch/scene_graph_example.launch
tesseract_ros/tesseract_examples/tesseract_ros_examples/package.xml
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/scene_graph_example.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/src/scene_graph_example_node.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/test/scene_graph_example_unit.cpp
tesseract_ros/tesseract_examples/tesseract_ros_examples/test/scene_graph_example_unit.test
tesseract_ros/tesseract_examples/tesseract_ros_examples/urdf/irb2400_iiwa_cowork.xacro

This example initializes 2 robots from a URDF. It then reattaches one of the robots to the end effector of the other robot. Here are some screenshots. Attached are the resulting .dot files
Before:
After:
[scene_graph_example.dot.txt](https://github.com/ros-industrial-consortium/tesseract/files/4182097/scene_graph_example.dot.txt)
[scene_graph_example_moveLink.dot.txt](https://github.com/ros-industrial-consortium/tesseract/files/4182098/scene_graph_example_moveLink.dot.txt)

Add tesseract_scene_graph_example

---

tesseract_ros/tesseract_monitoring/CMakeLists.txt

Missed a line that needed to be added to the CMakeLists.txt in order to expose the library to other ROS packages.

Adding contact monitor library to catkin package

---

tesseract/tesseract/include/tesseract/tesseract.h
tesseract/tesseract/include/tesseract/tesseract_init_info.h
tesseract/tesseract/src/tesseract.cpp
tesseract/tesseract_scene_graph/include/tesseract_scene_graph/graph.h

This adds a struct that contains information that can be used to recreate a Tesseract at the time of it's initialization. It is a prerequisite to a forthcoming tesseract_ros2 PR that will add the initial state to the TesseractState. Essentially this is storing the initial state which the Environment comand history builds on.

Add TesseractInitInfo

---

tesseract/tesseract_common/package.xml

Adding lcov similar to how we add clang. I got the error `lcov not found! Aborting...`  when I ran it without lcov. 
Rosdep key is lcov:https://github.com/ros/rosdistro/blob/5287b527aa3831decf1b34e26f6b8ca354a1307c/rosdep/base.yaml#L1482

Add lcov to package.xml

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/src/hybrid/descartes_trajopt_array_planner.cpp

This PR addresses two small issues I encountered when playing with Descartes and the Descartes TrajOpt hybrid planner:
- One error message is wrong, which lead to some head scratching. It talks about waypoints size, but is really related to the sampler size.
- The templated hybrid planner is never instantiated and is defined in a CPP, so attempting to use it results in undefined symbols. Just added two explicit instantiations to fix that issue.

Minor fixes for Descartes

---

tesseract/tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h
tesseract/tesseract_collision/include/tesseract_collision/core/common.h
tesseract/tesseract_collision/include/tesseract_collision/core/types.h
tesseract/tesseract_collision/src/fcl/fcl_utils.cpp

Modify the ContactTestData structure to use raw pointer instead of reference so members can be assigned and does not require the developer to use the constructor. This is beneficial if you want store this structure as a class member and reuse it for new contact requests instead of creating a new one each time. If there is a better way to accomplish this please provide suggestions.

Changes to tesseract_collision ContactTestData structure

---

.github/workflows/nightly.yml

Previously was getting `pull_request requires a map value` error. 
See [this example](https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request)

Fix Tesseract Nightly Workflow

---

.github/workflows/main.yml
tesseract/tesseract_collision/CMakeLists.txt
tesseract/tesseract_collision/include/tesseract_collision/core/types.h
tesseract/tesseract_collision/include/tesseract_collision/test_suite/benchmarks/benchmark_utils.hpp
tesseract/tesseract_collision/include/tesseract_collision/test_suite/benchmarks/collision_benchmarks.hpp
tesseract/tesseract_collision/package.xml
tesseract/tesseract_collision/test/benchmarks/CMakeLists.txt
tesseract/tesseract_collision/test/benchmarks/bullet_discrete_simple_benchmarks.cpp
tesseract/tesseract_common/cmake/tesseract_macros.cmake
tesseract/tesseract_geometry/include/tesseract_geometry/geometry.h

Adds the beginnings of a benchmarking framework for Tesseract Collision. Currently it adds tests for one manager running contactTest on primitives (this is 300 tests by itself). The idea is that I will add another benchmark executable for each manager. Then we can compare the outputs of each one as well as the outputs of each over time.
Additions
1.  Macro to run benchmarks similar to tests
2.  Benchmarking library in test_suite
3.  Google benchmark executable for BulletDiscreteManager
To test, build with `-DTESSERACT_ENABLE_BENCHMARKING=ON` and run the executable `/tests/benchmarks/tesseract_collision_bullet_discrete_simple_benchmarks`

Add Bullet Discrete Simple ContactTest Benchmarks

---

.github/workflows/benchmarking.yml
.github_actions_benchmarking.yml

Depends on #275 
Adds a separate workflow that builds and runs the benchmarks. The benchmark json output is then used to populate a gh_pages. [Here is an example result on my fork](https://mpowelson.github.io/tesseract/dev/bench/).[THIS](https://rhysd.github.io/github-action-benchmark/dev/bench/) is what it should look like over time. We will likely want to change the html later to make it a little more friendly since it currently makes one plot per benchmark. However, this should be a place to start. It works by reading in the json file, making changes to the html, and committing those changes to a gh-pages branch. 
Note: This will require some more setup from someone with more permissions that me before we will see any output (@Levi-Armstrong ). Notably we will need to set up an access …

Add Benchmarking Workflow

---

.github/workflows/benchmarking.yml

Cron jobs do not currently work due to [an issue](https://github.com/rhysd/github-action-benchmark/issues/24) in rhysd/github-action-benchmark. This temporarily disables them so I don't get emails every night telling me that it is broken.

Disable benchmarks in cron jobs

---

docs/index.html

The path was incorrect to the doxygen.
The Doxygen can be viewed through the link below.
https://ros-industrial-consortium.github.io/tesseract/doxygen/html/index.html

Update Docs index.html

---

tesseract/tesseract_collision/CMakeLists.txt
tesseract/tesseract_collision/cmake/tesseract_collision-config.cmake.in
tesseract/tesseract_collision/examples/CMakeLists.txt
tesseract/tesseract_collision/test/CMakeLists.txt
tesseract/tesseract_collision/test/benchmarks/CMakeLists.txt
tesseract/tesseract_geometry/CMakeLists.txt
tesseract/tesseract_geometry/cmake/tesseract_geometry-config.cmake.in

Something was not being exported correctly such that anything that used environment.h had to link against octomap. This has been fixed by switching to use the octomap targets.

Switch octomap to use CMake targets

---

.github/workflows/nightly.yml
tesseract/tesseract/colcon.pkg
tesseract/tesseract_collision/CMakeLists.txt
tesseract/tesseract_collision/colcon.pkg
tesseract/tesseract_common/cmake/tesseract_macros.cmake
tesseract/tesseract_common/colcon.pkg
tesseract/tesseract_environment/colcon.pkg
tesseract/tesseract_geometry/colcon.pkg
tesseract/tesseract_kinematics/colcon.pkg
tesseract/tesseract_planning/tesseract_motion_planners/colcon.pkg
tesseract/tesseract_planning/tesseract_process_planners/colcon.pkg
tesseract/tesseract_scene_graph/colcon.pkg
tesseract/tesseract_support/colcon.pkg
tesseract/tesseract_urdf/colcon.pkg
tesseract/tesseract_visualization/colcon.pkg
tesseract_python/tesseract_python/colcon.pkg
tesseract_python/tesseract_viewer_python/colcon.pkg

Addresses issue #302 as discussed on rosdep issue 724.

Add colcon.pkg files to all packages

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/hybrid/ompl_trajopt_freespace_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/src/hybrid/ompl_trajopt_freespace_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp

TrajOpt was happily copying the 2 state solution and moving on, which caused segfaults later on when > 2 states are assumed (it was indexing from -1 in places).

Bugfix when OMPL simplifies down to two states 

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp

These should be able to be const now since the request and response hold all of the data.

Tesseract planners: Make solve method const

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/types.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/problem_generators/default_problem_generator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/problem_generators/default_problem_generator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/problem_generators/default_problem_generator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/descartes_planner_tests.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp
tesseract/tesseract_planning/tesseract_process_managers/CMakeLists.txt
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/examples/raster_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_input.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_managers/simple_process_manager.h
tesseract/tesseract_planning/tesseract_process_managers/src/examples/freespace_manager_graph_example.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/motion_planner_process_generator.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_input.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/simple_process_manager.cpp

This PR adds two things. The first is a simple process manager which is very similar to freespace process manager which maybe deprecated in the near future. This is currently be used in the planning server to support a simple freespace process manager and simple cartesian process manager.
The second adds the ability to provide profile mapping for specific planners. This way in the command language you can have one profile for say Cartesian, then in this mapping you could provide a planner mapping to a specific profile. For example you could map the Cartesian profile for Descartes to DescartesToolZFree45 which has 45 degree sampling and for TrajOpt you could map it to a more specific or not provide a mapping.

Add simple process manager and planner profile remapping

---

tesseract_python/tesseract_viewer_python/CMakeLists.txt

There is a minor bug in the install part of the tesseract_viewer_python CMakeLists.txt. This pull request corrects the install.

Fix tesseract_viewer_python install Python executable in CMakeLists.txt

---

tesseract/tesseract/include/tesseract/tesseract.h
tesseract/tesseract/src/tesseract.cpp
tesseract/tesseract_collision/include/tesseract_collision/core/continuous_contact_manager_factory.h
tesseract/tesseract_collision/include/tesseract_collision/core/discrete_contact_manager_factory.h
tesseract/tesseract_environment/src/core/environment.cpp
tesseract/tesseract_scene_graph/src/graph.cpp
tesseract/tesseract_visualization/CMakeLists.txt
tesseract/tesseract_visualization/include/tesseract_visualization/ignition/conversions.h
tesseract/tesseract_visualization/include/tesseract_visualization/ignition/entity_manager.h
tesseract/tesseract_visualization/include/tesseract_visualization/ignition/tesseract_ignition_visualization.h
tesseract/tesseract_visualization/src/ignition/conversions.cpp
tesseract/tesseract_visualization/src/ignition/entity_manager.cpp
tesseract/tesseract_visualization/src/ignition/tesseract_ignition_visualization.cpp
tesseract/tesseract_visualization/src/visualization_loader.cpp

This also adds the tesseract ignition visualization which gets built only if ignition is found. This was moved from tesseract_ignition because dynamically loading a library was problematic, but may find a solution in the near future.

Improve tesseract init and add reset function

---

tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp

In the current code version both the continuous_manager and the adjacency_map are declared but unused; the active collision objects used for the collision check consequently default to all the active objects in the environment (meaning that unaffected parts of the system are checked too).
With this PR, the Active collision objects for the final collision check are set to those of the Kinematic chain affected by the plan.

Setting Active collision objects for the contact managers in trajopt motion planner

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/profile/descartes_default_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/profile/ompl_default_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/profile/trajopt_default_composite_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_collision_config.h
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_planner_tests.cpp
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/continuous_contact_check_process_generator.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/discrete_contact_check_process_generator.h

The challenge I keep running into with continuous collision checking is that if you have two kinematic links that are always within say 2cm and are not disabled in ACM. Then if you move more than 2cm in a single time step it will report collision because the end state of the first shape overlaps with the start state of the second shape. This switches the default to leverage Discrete Continuous which will make motion planning more stable and will use casted collision checking in the post check with a fine resolution to catch collisions if the planners longest valid segment length was not set fine enough.

Update default longest valid segment length and set default to use discrete continuous.

---

tesseract/tesseract_planning/tesseract_process_managers/examples/freespace_manager_example.cpp
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_manager_example.cpp
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/taskflows/freespace_taskflow.h
tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/freespace_taskflow.cpp
tesseract/tesseract_planning/tesseract_process_managers/test/tesseract_process_managers_unit.cpp

Through testing it was found for the global planner that since Descartes was already ran as the global planner that running TrajOpt first succeeds more often that it does not. This switches it to try TrajOpt first then if it fails it will then try OMPL followed by TrajOpt.

Improve global raster taskflow

---

tesseract/tesseract_kinematics/include/tesseract_kinematics/ikfast/external/ikfast.h

The [Cpp Core Guidelines](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#con2-by-default-make-member-functions-const) recommends against forcing `const` on function return types and function parameters that are not references or pointers. The user can decide if they want to store the function return variable into a const or not. If you use Clang-Tidy, warnings will be produced, but since this does not have a test that leverages this header it was not found until recently when using it in another project.
Given:
`const int test(const int i)`
Should be:
`int test(int i)`

Remove const from return type in ikfast.h

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_collision_config.h
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/profile/trajopt_default_composite_profile.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_collision_config.cpp

I imagine this was an oversite, but costs had a "buffer_margin" and constraints had a "safety_margin". I renamed this so that they are both the same. 
Note: this is a breaking change.

Fix safety margin name

---

tesseract/tesseract_collision/CMakeLists.txt
tesseract/tesseract_collision/cmake/tesseract_collision-config.cmake.in
tesseract/tesseract_collision/examples/CMakeLists.txt
tesseract/tesseract_collision/test/CMakeLists.txt
tesseract/tesseract_collision/test/benchmarks/CMakeLists.txt
tesseract/tesseract_common/include/tesseract_common/utils.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/cartesian_waypoint.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/composite_instruction.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/joint_waypoint.h
tesseract/tesseract_planning/tesseract_command_language/src/composite_instruction.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp

Having the CompositeInstruction inherit directly form std:vector was going to make python wrapper very difficult or even impossible leveraging SWIG. Same issues exists for the JointWaypoint and CartesianWaypoint. This remove the inheritance and adds all of the container methods required.

Remove inheritance of std::vector from Composite Instruction

---

tesseract/tesseract_planning/tesseract_process_managers/src/process_managers/simple_process_manager.cpp

The callback was using a reference to a local variable causing a runtime error.

Fix done and error callback in simple process manager

---

tesseract/tesseract_scene_graph/include/tesseract_scene_graph/srdf/groups.h

This tuple is constructed in the wrong order.
The puzzle piece examples (tesseract_ros) on master branch were not working due to this issue.

Fixed SRDF parse

---

tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/command_language.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/composite_instruction.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/constants.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/move_instruction.h
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/plan_instruction.h
tesseract/tesseract_planning/tesseract_command_language/src/composite_instruction.cpp
tesseract/tesseract_planning/tesseract_command_language/src/move_instruction.cpp
tesseract/tesseract_planning/tesseract_command_language/src/plan_instruction.cpp
tesseract/tesseract_planning/tesseract_command_language/test/serialize_test.cpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/problem_generators/default_problem_generator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/planner_utils.h
tesseract/tesseract_planning/tesseract_motion_planners/src/core/planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/utils_test.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/iterative_spline_parameterization_process_generator.cpp

Consolidates all of the profile remapping into a single utility that gets used everywhere. Addresses #391. Note that all planners should now set a "DEFAULT" profile

Add utility for getting profiles

---

.github/workflows/bionic_build.yml
.github/workflows/xenial_build.yml
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/interface_utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/simple/profile/simple_planner_default_lvs_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/lvs_interpolation.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/descartes_planner_tests.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_planner_tests.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/simple_planner_lvs_interpolation.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/trajopt_planner_tests.cpp
tesseract/tesseract_planning/tesseract_process_managers/CMakeLists.txt
tesseract/tesseract_planning/tesseract_process_managers/examples/freespace_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/examples/freespace_manager_example.cpp
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_dt_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_manager_example.cpp
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_waad_dt_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/examples/raster_waad_example_program.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/seed_min_length_process_generator.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/taskflows/cartesian_taskflow.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/taskflows/ompl_taskflow.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/taskflows/trajopt_taskflow.h
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/seed_min_length_process_generator.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/cartesian_taskflow.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/freespace_taskflow.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/ompl_taskflow.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/taskflows/trajopt_taskflow.cpp
tesseract/tesseract_planning/tesseract_process_managers/test/CMakeLists.txt
tesseract/tesseract_planning/tesseract_process_managers/test/tesseract_process_managers_unit.cpp

This rebases PR #398 on master
I ran into issues getting this to fully function as the default because TrajOpt requires a minimum set states for joint velocity, acceleration, and jerk smoothing. This is also an issue with the interpolate and assign components but the defaults handled but you end up with a large number of states because this was manager a the plan instruction where the number of states were set. I looked at adding a composite profile for the simple planner but it quickly became difficult especially when you got to the raster planners because the simple planner is not aware of how the program would be broken up. Instead I created a process generator to handle this which increases the seed length only in the case where TrajOpt is used in the task flow. This check the input …

Fix simple lvs tests

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_robot_sampler.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_vertex_evaluator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_robot_sampler.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/profile/descartes_default_plan_profile.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/profile/descartes_default_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/types.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/ompl_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/simple/simple_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/trajopt/trajopt_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/package.xml
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/ompl_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_motion_planner.cpp

This PR creates a vertex validator and vertex allocator that take a descartes problem similar to the edge evaluator. Also adds missing delete constructors for the motion planners base class.
@mpowelson  I wanted to let you know, in case you are using Descartes planner, this is a breaking change if you are explicitly setting the is_valid for he Descartes profile.

Add vertex evaluator to descartes

---

tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/simple/simple_motion_planner.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/simple/step_generators/lvs_interpolation.h
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/lvs_interpolation.cpp
tesseract/tesseract_planning/tesseract_process_managers/test/tesseract_process_managers_unit.cpp

I noticed odd behavior in the LVS interpolator and Simple Planner. After investigating the LVS interpolator was not correctly handling failure modes for conditions with joint/cartesian, cartesian/joint and cartesian/cartesian. There was also an issue in the simple planner where it was not resetting the start waypoint when processing composite instructions because the variable was being passed as const& instead of by reference.

Fix issues in LVS Interpolator and Simple Planner

---

tesseract/tesseract/src/tesseract.cpp
tesseract/tesseract_environment/include/tesseract_environment/core/environment.h
tesseract/tesseract_environment/include/tesseract_environment/core/manipulator_manager.h
tesseract/tesseract_environment/src/core/environment.cpp
tesseract/tesseract_environment/src/core/manipulator_manager.cpp
tesseract/tesseract_environment/test/tesseract_environment_unit.cpp
tesseract/tesseract_kinematics/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp
tesseract/tesseract_kinematics/src/core/rep_inverse_kinematics.cpp
tesseract/tesseract_kinematics/src/core/rop_inverse_kinematics.cpp
tesseract/tesseract_kinematics/src/kdl/kdl_fwd_kin_chain.cpp
tesseract/tesseract_kinematics/src/kdl/kdl_fwd_kin_tree.cpp
tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_lma.cpp
tesseract/tesseract_kinematics/src/kdl/kdl_inv_kin_chain_nr.cpp
tesseract/tesseract_kinematics/src/opw/opw_inv_kin.cpp

This update code base to leverage the kinematics setLimits for environment commands that changes kinematic limits. This was required to solve the issue for opw and ikfast which do not store the scene_graph and did not what to change the interface. @mpowelson Do you mind testing to make sure this still works for you? I am currently testing it on my end to confirm it solves the issues we are having related to ikfast kinematics objects not having its limits updated.

Update to leverage kinematics setLimits for environment changes

---

tesseract/tesseract_collision/include/tesseract_collision/core/types.h
tesseract/tesseract_common/include/tesseract_common/types.h
tesseract/tesseract_environment/include/tesseract_environment/core/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/trajectory_validator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision_edge_evaluator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision_edge_evaluator.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/profile/descartes_default_plan_profile.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/profile/descartes_default_plan_profile.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/continuous_contact_check_process_generator.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/discrete_contact_check_process_generator.h
tesseract/tesseract_planning/tesseract_process_managers/include/tesseract_process_managers/process_generators/fix_state_collision_process_generator.h
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/continuous_contact_check_process_generator.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/discrete_contact_check_process_generator.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/process_generators/fix_state_collision_process_generator.cpp
tesseract/tesseract_planning/tesseract_process_managers/test/fix_state_collision_process_generator_unit.cpp

Create a common config for collision checking 

---

tesseract/tesseract_scene_graph/include/tesseract_scene_graph/graph.h
tesseract/tesseract_scene_graph/src/graph.cpp

Indeed, it does not (and should not) modify the underlying graph.
I noticed this while trying to compute link paths on an existing environment, where the SceneGraph is `const`. I'm not sure why it wasn't const in the first place, so my suggestion might not be valid. In any case don't hesitate to modify this branch as you see fit.

Make getShortestPath const

---

tesseract/tesseract_kinematics/include/tesseract_kinematics/opw/opw_inv_kin.h

Indeed, the header uses CONSOLE_BRIDGE_logError but does not include the
relevant header, which means that including only that header causes
compilation errors.
I encountered this while trying to write a simple program that would only load some OPW kinematics parameters and check them... Again, please feel free to modify that branch to suit your liking!

Add forgotten include in opw_inv_kin.h

---

tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/trajopt_utils.cpp

The size should be `(end_index - start_index) + 1` instead of `(end_index - start_index)`

Fix bug in createCollisionTermInfo

---

tesseract/tesseract_kinematics/src/opw/opw_inv_kin.cpp

The error message when attempting to use a non-implemented method in OPWInvKin mentions IKFastInvKin, so update that as it's probably a copy-paste error.

Fix error message IKFast -> OPW

---

tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/config/trajopt_planner_default_config.cpp
tesseract_python/tesseract_python/swig/trajopt/problem_description.i

This PR updates the `TrajoptPlannerDefaultConfig` class to utilize the `fixed_timesteps` parameter of the TrajOpt PCI (added in [this TrajOpt PR](https://github.com/ros-industrial-consortium/trajopt_ros/pull/226), formerly called `dofs_fixed`). This will help prevent solver failures caused by costs being added to timesteps of the optimization where the variables are fixed

Utilize `fixed_timesteps` parameter in TrajOpt planner

---

tesseract/tesseract_common/include/tesseract_common/manipulator_info.h
tesseract/tesseract_common/src/manipulator_info.cpp
tesseract/tesseract_planning/tesseract_command_language/include/tesseract_command_language/utils/utils.h
tesseract/tesseract_planning/tesseract_command_language/src/utils/utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/core/utils.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_motion_planner.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/problem_generators/default_problem_generator.h
tesseract/tesseract_planning/tesseract_motion_planners/src/core/utils.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/simple_motion_planner.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/fixed_size_assign_position.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/fixed_size_interpolation.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/simple/step_generators/lvs_interpolation.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/problem_generators/default_problem_generator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/trajopt/profile/trajopt_default_plan_profile.cpp
tesseract/tesseract_planning/tesseract_process_managers/src/core/process_planning_server.cpp

This finishes out support for external tcp to support all examples in tesseract_ros_examples.
The last commit addresses issue #498.

Add support for external tcp attached to kinematic link

---

README.md

The readme currently has the following for test instructions:
`catkin test --no-deps tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_planners tesseract_scene_graph tesseract_urdf`
Which still uses the old `tesseract_process_planners` package, and doesn't include python. This pull request changes the instructions to:
`catkin test --no-deps tesseract_collision tesseract_common tesseract_environment tesseract_geometry tesseract_kinematics tesseract_motion_planners tesseract_process_managers tesseract_scene_graph tesseract_urdf tesseract_python`

Fix readme instructions for testing 

---

tesseract/tesseract_common/cmake/tesseract_macros.cmake
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/descartes_collision.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/descartes_collision.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/impl/profile/descartes_default_plan_profile.hpp
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/descartes/profile/descartes_default_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/continuous_motion_validator.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/profile/ompl_default_plan_profile.h
tesseract/tesseract_planning/tesseract_motion_planners/include/tesseract_motion_planners/ompl/state_collision_validator.h
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/continuous_motion_validator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/profile/ompl_default_plan_profile.cpp
tesseract/tesseract_planning/tesseract_motion_planners/src/ompl/state_collision_validator.cpp
tesseract/tesseract_planning/tesseract_motion_planners/test/ompl_planner_tests.cpp

I did not update trajopt because it has its own data structure. While we could go through and update it, I'd rather just focus on getting the ifopt planner working.
Similarly I added the ContactMarginData to OMPL but did not use the CollisionCheckConfig since OMPL handles LVS itself. I thought it would be confusing to have 2 longest valid segment terms where only one gets used.
Closes #427

Update planners to use CollisionCheckConfig

---

tesseract/tesseract_collision/include/tesseract_collision/core/common.h
tesseract/tesseract_geometry/include/tesseract_geometry/mesh_parser.h

The current approach does consider contact if the threshold and the distance are equal. So if the contact threshold is set to zero and the distance is zero this is not considered in contact. This switches the logic so if the threshold and distance are equal then it is considered in contact which is he behavior in the master branch.

Update processResults in tesseract_collision distance check

---

tesseract_visualization/include/tesseract_visualization/markers/arrow_marker.h
tesseract_visualization/include/tesseract_visualization/markers/axis_marker.h
tesseract_visualization/include/tesseract_visualization/markers/contact_results_marker.h
tesseract_visualization/include/tesseract_visualization/markers/geometry_marker.h
tesseract_visualization/include/tesseract_visualization/markers/marker.h
tesseract_visualization/include/tesseract_visualization/markers/toolpath_marker.h

These extra commands are needed for the SWIG wrappers.

Add SWIG shared_ptr commands to visualization markers

---

tesseract_common/include/tesseract_common/any.h
tesseract_common/include/tesseract_common/serialization.h
tesseract_common/test/tesseract_common_unit.cpp

@mpowelson This is to support serializing the profile Dictionary. This is an any type erasure which does not expect any specific interface.

Add serializable any type erasure

---

tesseract_visualization/src/trajectory_interpolator.cpp

This is important if you want to visualize trajectories that resulted from a failed motion request for instance.

Modify trajectory interpolator to visualize trajectories w/o time

---

tesseract_collision/package.xml
tesseract_environment/include/tesseract_environment/core/environment.h
tesseract_environment/package.xml
tesseract_environment/src/core/environment.cpp
tesseract_environment/src/core/manipulator_manager.cpp
tesseract_environment/test/CMakeLists.txt
tesseract_environment/test/tesseract_environment_unit.cpp
tesseract_kinematics/include/tesseract_kinematics/core/rep_inverse_kinematics.h
tesseract_kinematics/include/tesseract_kinematics/core/rop_inverse_kinematics.h
tesseract_kinematics/src/core/rep_inverse_kinematics.cpp
tesseract_kinematics/src/core/rop_inverse_kinematics.cpp
tesseract_scene_graph/include/tesseract_scene_graph/kinematics_information.h
tesseract_scene_graph/include/tesseract_scene_graph/srdf/group_rep_kinematics.h
tesseract_scene_graph/include/tesseract_scene_graph/srdf/group_rop_kinematics.h
tesseract_scene_graph/test/tesseract_scene_graph_srdf_unit.cpp

The ROP and REP rely on sampling of the positioner axes so it it nice to have the ability to create to different solvers for the sample manipulator with different sampling resolutions. This enables the ability to construct the ROP and REP kinematics with a provided solver name. Also updates the SRDF to support providing a solver name which is optional.
Edit:
Also include a bug fix Environment applyCommands not correctly locking the mutex.

Add ability to construct ROP and REP kinematic solver with different solver names

---

tesseract_common/src/kinematic_limits.cpp
tesseract_common/test/tesseract_common_unit.cpp

While browsing recent changes, I noticed a bug in the new enforce_joint_limits function:
Up to now, it would incorrectly apply the upper limit to any position
that's outside the range. For example, a position that's slightly under
the lower limit would get assigned the upper limit. Fix this by using
Eigen's min and max functions, resulting in a proper clamp.
To test this:
```cpp
Eigen::VectorXd test = Eigen::VectorXd::Constant(6, -2);
Eigen::MatrixXd limits(6, 2);
limits.col(0) = Eigen::VectorXd::Constant(6, -1);
limits.col(1) = Eigen::VectorXd::Constant(6, 1);
enforcePositionLimits(test, limits);
std::cout << test.transpose() << std::endl;
```
Before:
```
1 1 1 1 1 1
```
After
```
-1 -1 -1 -1 -1 -1
```

Fixup enforceJointLimits

---

tesseract_collision/include/tesseract_collision/test_suite/benchmarks/large_dataset_benchmarks.hpp
tesseract_collision/include/tesseract_collision/test_suite/benchmarks/primatives_benchmarks.hpp

The API for `tesseract_collision::DiscreteContactManager` changed, but benchmark code was not updated accordingly. This PR corrects that oversight and fixes a couple of warnings.
To test locally, simply build and run the benchmarks (e.g., with `--cmake-args -DTESSERACT_ENABLE_BENCHMARKING=Yes`). Presumably, this will allow the benchmarks to be run in CI as well.
On a side note, it would be nice to be able to build the benchmarks without running them immediately, but that's a separate issue.

Update benchmarks after API change in discrete contact manager

---

tesseract_collision/include/tesseract_collision/bullet/bullet_utils.h
tesseract_collision/include/tesseract_collision/core/common.h
tesseract_collision/src/bullet/bullet_discrete_bvh_manager.cpp
tesseract_environment/test/CMakeLists.txt
tesseract_environment/test/tesseract_environment_collision.cpp
tesseract_visualization/src/trajectory_interpolator.cpp
tesseract_visualization/src/trajectory_player.cpp
tesseract_visualization/test/trajectory_player_unit.cpp

Bullet does some optimization check to prevent necessary updates to broadphase which does not get triggered when setting active links. This add a function to refresh the broadphase when active links change.
Also fixes an issue in the trajectory player where it does not update the finished bool if the duration is set the max.

Fix issues with Bullet Broadphase and Trajectory Player

---

tesseract_collision/CMakeLists.txt
tesseract_common/CMakeLists.txt
tesseract_environment/CMakeLists.txt
tesseract_geometry/CMakeLists.txt
tesseract_kinematics/CMakeLists.txt
tesseract_scene_graph/CMakeLists.txt
tesseract_urdf/CMakeLists.txt
tesseract_visualization/CMakeLists.txt

The `tesseract_variables()` macro must be called before use of tesseract variables so they are correctly configured.

Move tesseract_variables() before any use of custom macros

---

tesseract_environment/include/tesseract_environment/core/environment.h
tesseract_environment/src/core/environment.cpp

I was trying to figure out how best to determine if the current state in the environment has changes because we are not tracking this in the environment history. Adding a timestamp looks like the simplest approach where the developer can store the timestamp and then check if it is different to know if the state has changed.

Store timestamp when environment state is set

---

tesseract_kinematics/include/tesseract_kinematics/core/utils.h
tesseract_kinematics/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp
tesseract_kinematics/src/kdl/kdl_inv_kin_chain_lma.cpp
tesseract_kinematics/src/kdl/kdl_inv_kin_chain_nr.cpp
tesseract_kinematics/src/opw/opw_inv_kin.cpp
tesseract_kinematics/src/ur/ur_inv_kin.cpp
tesseract_kinematics/test/kinematics_core_unit.cpp

This PR:
- Removes the addition of redundant solutions to the output of the inverse kinematic solvers
- Returning redundant IK solutions with nominal solutions can cause downstream applications to repeat operations because those applications cannot disambiguate the two types of solutions. For example, the Tesseract Descartes planner collision checks all generated IK solutions, resulting in a lot of unnecessary repeated work when the vast majority of IK solutions are just redundancies of a solution that has already been checked.
- Applications requiring redundant solutions should use the provided utility function to produce them from a nominal solution
- Adds a function for generating a list of indices which indicate which joints in a input list are capable of generating redundant …

IK Solver Redundant Solutions Update

---

tesseract_collision/include/tesseract_collision/core/common.h
tesseract_environment/CMakeLists.txt
tesseract_environment/include/tesseract_environment/core/environment.h
tesseract_environment/include/tesseract_environment/core/utils.h
tesseract_environment/src/core/environment.cpp
tesseract_environment/src/core/utils.cpp
tesseract_environment/test/tesseract_environment_unit.cpp
tesseract_scene_graph/include/tesseract_scene_graph/graph.h
tesseract_scene_graph/src/graph.cpp

This adds the following
- Update Environment to get active link names provided a list of joint. This is used by motion planning to determine what links are active for a given manipulator.
- Update Environment to static link names and static link names provided a list of joints
- A utility function which uses active and static link names to generate a list of possible contact pairs.

Add support function for getting active and static links along with collision pairs

---

tesseract_kinematics/core/src/kinematic_group.cpp
tesseract_kinematics/core/src/rep_inv_kin.cpp
tesseract_kinematics/core/src/rop_inv_kin.cpp
tesseract_kinematics/ikfast/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_fwd_kin_chain.h
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_lma.h
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr.h
tesseract_kinematics/kdl/src/kdl_fwd_kin_chain.cpp
tesseract_kinematics/kdl/src/kdl_inv_kin_chain_lma.cpp
tesseract_kinematics/kdl/src/kdl_inv_kin_chain_nr.cpp
tesseract_kinematics/opw/src/opw_inv_kin.cpp
tesseract_kinematics/ur/src/ur_inv_kin.cpp

Add determinant check to each inverse kinematics solver on the incoming pose.
Also, it turns out that KDL is not thread-safe because the Joint class leverages mutable variables. This add mutex to the solvers to resolve the issue and also opened an issue on KDL's repository.

Add determinant check and make kdl solvers thread safe

---

tesseract_collision/test/collision_margin_data_unit.cpp
tesseract_common/include/tesseract_common/collision_margin_data.h

This add an override type that allows you to modify both the default margin and pair margins which was not possible.

Add contact margin data override type MODIFY

---

README.md
dependencies.rosinstall
dependencies_with_ext.rosinstall
tesseract_environment/src/environment.cpp

Some kinematics groups could depend on the state of the environment which contain other joints so the environment cache should be cleared on state changed.

Fix KinematicGroup and JointGroup cache to clear on current state change

---

tesseract_kinematics/core/include/tesseract_kinematics/core/utils.h
tesseract_kinematics/ikfast/include/tesseract_kinematics/ikfast/ikfast_inv_kin.h
tesseract_kinematics/ikfast/include/tesseract_kinematics/ikfast/impl/ikfast_inv_kin.hpp
tesseract_kinematics/opw/src/opw_inv_kin.cpp
tesseract_kinematics/test/abb_irb2400_ikfast_kinematics.cpp
tesseract_kinematics/test/iiwa7_ikfast_kinematics.cpp
tesseract_kinematics/test/kinematics_core_unit.cpp
tesseract_kinematics/ur/src/ur_inv_kin.cpp

This function cannot be used to harmonize non-revolute joints. The redundancy cable joints identifies which joint has the possibility of redundant solutions. For example this should not be applied to prismatic joints.

Add redundancy capable joints to the harmonizeTowardZero function

---

.github/workflows/codecov.yml
tesseract_collision/core/include/tesseract_collision/core/types.h
tesseract_collision/core/include/tesseract_collision/core/utils.h
tesseract_collision/core/src/continuous_contact_manager.cpp
tesseract_collision/core/src/discrete_contact_manager.cpp
tesseract_collision/core/src/utils.cpp
tesseract_environment/test/tesseract_environment_utils.cpp

Adds the ability to enable/disable links from the contact manager config. The reasoning here is similar to having the acm in the config. You might want to completely disable some links for some planning Tasks and re-enable them for others.

Add modify_object_enabled to ContactManagerConfig

---

.clang-tidy
.github/workflows/api_docs.yml
.github/workflows/benchmarking.yml
.github/workflows/nightly.yml
tesseract_collision/bullet/include/tesseract_collision/bullet/bullet_utils.h
tesseract_collision/bullet/src/bullet_factories.cpp
tesseract_collision/bullet/src/tesseract_convex_convex_algorithm.cpp
tesseract_collision/bullet/src/tesseract_gjk_pair_detector.cpp
tesseract_collision/fcl/src/fcl_factories.cpp
tesseract_collision/test/CMakeLists.txt
tesseract_common/include/tesseract_common/utils.h
tesseract_common/src/utils.cpp
tesseract_common/test/test_plugin_multiply.cpp
tesseract_environment/src/environment.cpp
tesseract_geometry/include/tesseract_geometry/impl/octree.h
tesseract_kinematics/core/CMakeLists.txt
tesseract_kinematics/core/include/tesseract_kinematics/core/validate.h
tesseract_kinematics/core/src/rep_factory.cpp
tesseract_kinematics/core/src/rop_factory.cpp
tesseract_kinematics/core/src/validate.cpp
tesseract_kinematics/kdl/src/kdl_factories.cpp
tesseract_kinematics/opw/src/opw_factory.cpp
tesseract_kinematics/test/kinematics_test_utils.h
tesseract_kinematics/ur/src/ur_factory.cpp
tesseract_scene_graph/include/tesseract_scene_graph/link.h

Previously this was called in the motion planners resulting in multiple calls impacting planning time. This has been moved here to only run when a new instance of the kinematics object is created.

Move checkKinematics to getKinematicGroup and add support for clang-tidy-12

---

.github/workflows/bionic_build.yml
.github/workflows/focal_build.yml

Currently a docker is create for major.minor.patch but this also adds one with just major.minor which will be used for other CI pipelines to avoid having to frequently update other CI pipelines for patch versions.

Add docker creation for major.minor

---

.github/workflows/bionic_build.yml
.github/workflows/focal_build.yml

It looks like type=semver expects the tag to start with a `v` so switching to pep440.

Switch docker build to use pep440

---

.github/workflows/bionic_build.yml
.github/workflows/focal_build.yml

Fix docker push

---

tesseract_collision/core/include/tesseract_collision/core/types.h

Not needed since C++11 and this header puts placeholder objects in the global namespace on system-installed Boost versions

Remove unneeded boost bind include

---

.github/workflows/bionic_build.yml
.github/workflows/codecov.yml
.github/workflows/focal_build.yml
tesseract_common/include/tesseract_common/types.h
tesseract_common/include/tesseract_common/yaml_utils.h
tesseract_common/src/types.cpp
tesseract_common/test/tesseract_common_unit.cpp
tesseract_common/test/utils_unit.cpp
tesseract_environment/src/environment.cpp
tesseract_srdf/CMakeLists.txt
tesseract_srdf/include/tesseract_srdf/configs.h
tesseract_srdf/include/tesseract_srdf/srdf_model.h
tesseract_srdf/src/configs.cpp
tesseract_srdf/src/srdf_model.cpp
tesseract_srdf/test/tesseract_srdf_unit.cpp
tesseract_support/urdf/abb_irb2400_calibration.yaml
tesseract_support/urdf/malformed_config.yaml

The current calibration config support defining a joint origin in a yaml config file which gets loaded through the srdf. In the environment it will apply these as a `ChangeJointOriginCommand`.
``` yaml
calibration:
joints:
joint_1:
position:
x: 1
y: 2
z: 3
orientation:
x: 0
y: 0
z: 0
w: 1
joint_2:
position:
x: 4
y: 5
z: 6
orientation:
x: 0
y: 0
z: 0
w: 1
```
srdf element:
``` xml
<calibration_config filename="calibration_config.yaml"/>
```

Add ability to provide calibration information in the SRDF

---

tesseract_collision/bullet/CMakeLists.txt
tesseract_environment/include/tesseract_environment/commands/add_allowed_collision_command.h

The three commits here:
- Bullet extras are not easily obtained on Windows so this makes building the HACD convex decomposition library optional
- Paths to bullet are specified as `${BULLET_ROOT_DIR}/${BULLET_INCLUDE_DIRS}`, e.g., but the include dirs already contains absolute paths. ~Probably this wasn't noticed on Ubuntu since it would already be looking in the system install dirs.~ This is a result of packaging for vcpkg and is different from the version packaged for Ubuntu.
- Had a compile error since a header used but didn't include `std::string`

A few fixes that were needed for Windows

---

tesseract_srdf/include/tesseract_srdf/utils.h
tesseract_srdf/src/srdf_model.cpp
tesseract_srdf/src/utils.cpp
tesseract_srdf/test/tesseract_srdf_unit.cpp

Sorts the ACM alphabetically when writing it. This is motivated by [this](https://github.com/tesseract-robotics/tesseract_ignition/issues/8) issue. With this change the allowed collisions in the generated SRDF will be sorted alphabetically first by the first link and then by the second link. This does not address that I assume it is possible that which link is the first/second link in the pair could be flipped. We may want to address that in the future too if we want generated SRDFs to be the same run to run. That could be done here, but it might make more sense to do that when we create the pairs.

Sort ACM alphabetically when writing

---

tesseract_kinematics/core/include/tesseract_kinematics/core/types.h

As discussed in #712, `UR10eParameters`, `UR5eParameters` and `UR3eParameters` values were slightly off compared to official documentation. This PR corrects them to match the values found [here](https://www.universal-robots.com/articles/ur/application-installation/dh-parameters-for-calculations-of-kinematics-and-dynamics/).

Update UR Kinematics Parameters for e-series

---

.github/workflows/windows_noetic_build.yml

`windows-latest` is defaulting to `windows-2022` for the Windows GitHub CI action. ROS Noetic uses Visual Studio 2019, so change instance to `windows-2019` in `windows_noetic_build.yml`.

Use windows-2019 for github action

---

tesseract_urdf/CMakeLists.txt

This does not change the comment above the if() statement. I tested with BOOST_VERSION and Boost_VERSION and did not see any different. The if() block is not entered with boost-1.71.0 with the current version check.

Modifying Boost_VERSION check to use semver

---

tesseract_collision/core/include/tesseract_collision/core/contact_managers_plugin_factory.h
tesseract_collision/core/include/tesseract_collision/core/continuous_contact_manager.h
tesseract_collision/core/include/tesseract_collision/core/discrete_contact_manager.h
tesseract_common/include/tesseract_common/allowed_collision_matrix.h
tesseract_common/include/tesseract_common/types.h
tesseract_environment/include/tesseract_environment/commands.h
tesseract_environment/include/tesseract_environment/environment.h
tesseract_geometry/include/tesseract_geometry/geometries.h
tesseract_geometry/include/tesseract_geometry/geometry.h
tesseract_geometry/include/tesseract_geometry/impl/mesh.h
tesseract_geometry/include/tesseract_geometry/impl/polygon_mesh.h
tesseract_geometry/include/tesseract_geometry/impl/sdf_mesh.h
tesseract_kinematics/core/include/tesseract_kinematics/core/forward_kinematics.h
tesseract_kinematics/core/include/tesseract_kinematics/core/inverse_kinematics.h
tesseract_kinematics/core/include/tesseract_kinematics/core/joint_group.h
tesseract_kinematics/core/include/tesseract_kinematics/core/kinematic_group.h
tesseract_kinematics/core/include/tesseract_kinematics/core/kinematics_plugin_factory.h
tesseract_kinematics/core/include/tesseract_kinematics/core/types.h
tesseract_scene_graph/include/tesseract_scene_graph/graph.h
tesseract_scene_graph/include/tesseract_scene_graph/joint.h
tesseract_scene_graph/include/tesseract_scene_graph/link.h
tesseract_srdf/src/srdf_model.cpp
tesseract_state_solver/include/tesseract_state_solver/kdl/kdl_state_solver.h
tesseract_state_solver/include/tesseract_state_solver/mutable_state_solver.h
tesseract_state_solver/include/tesseract_state_solver/ofkt/ofkt_state_solver.h
tesseract_state_solver/include/tesseract_state_solver/state_solver.h

This pull request contains patches for the Feb 2022 python update.

Python patches for Feb 2022 update

---

tesseract_urdf/CMakeLists.txt

This PR fixes the problem with #714 by checking for the existence of `Boost_VERSION_MACRO`
> This fix is not going to work with older versions of cmake. FindBoost returns Boost_VERSION in macro format up until cmake version 3.15, then changes to semver and adds Boost_VERSION_MACRO to return the old format. Ubuntu Bionic uses cmake 3.10, so it is going to cause a problem.

Fix Boost_VERSION in tesseract_urdf to check for Boost_VERSION_MACRO

---

tesseract_scene_graph/examples/CMakeLists.txt

This popped up when building against a ROS2 source build. Not sure why it wasn't apparent before.

Fix incorrect linking to console_bridge

---

tesseract_common/include/tesseract_common/class_loader.hpp

`boost::dll::import` -> `boost::dll::import_symbol`
https://www.boost.org/users/history/version_1_76_0.html

Boost dll api change in 1.76+

---

tesseract_environment/include/tesseract_environment/environment_monitor.h
tesseract_environment/include/tesseract_environment/environment_monitor_interface.h

I have added a interface for the environment monitor to tesseract_environment to support Tesseract Robotic Studio. This will allow for a single widget to be used with different environment monitors leveraging ROS1, ROS2, Ignition Transport, etc.

Add environment monitor interfaces

---

tesseract_environment/include/tesseract_environment/environment.h
tesseract_environment/src/environment.cpp

The initial implementation called all of the event callback under a unique lock. This was problematic because you could not call any of the environment method without causing a dead lock. This updated so the event callback are under a shared lock so the environment can be accessed.

Update triggering of event callbacks to take a shared lock

---

tesseract_collision/bullet/src/bullet_cast_simple_manager.cpp

`cows_` in BulletCastSimpleManager sometimes uses `cast_cow` in one of the vectors instead of the uncast `cow`. This mismatch was resulting in a segfault on the lines changed. Search by name directly to avoid this problem.

Fix invalid iterator in bullet_cast_simple_manager

---

tesseract_collision/bullet/include/tesseract_collision/bullet/bullet_utils.h
tesseract_collision/bullet/src/bullet_utils.cpp

Originally it was creating a new collision shape for each occupied cell when it only need to be creating one for each depth.

Reduce bullet octomap storage

---

.github/workflows/benchmarking.yml
.run_combine_benchmark_results
tesseract_collision/bullet/CMakeLists.txt
tesseract_collision/bullet/src/tesseract_compound_compound_collision_algorithm.cpp
tesseract_collision/core/include/tesseract_collision/test_suite/benchmarks/large_dataset_benchmarks.hpp
tesseract_collision/core/include/tesseract_collision/test_suite/benchmarks/primatives_benchmarks.hpp
tesseract_collision/fcl/CMakeLists.txt
tesseract_collision/test/benchmarks/CMakeLists.txt
tesseract_collision/test/benchmarks/bullet_discrete_bvh_benchmarks.cpp
tesseract_collision/test/benchmarks/bullet_discrete_simple_benchmarks.cpp
tesseract_collision/test/benchmarks/fcl_discrete_bvh_benchmarks.cpp
tesseract_collision/vhacd/CMakeLists.txt

- Remove no longer needed 
``` cmake
include_directories(BEFORE "${BULLET_INCLUDE_DIRS_ABS}")
link_directories(BEFORE "${BULLET_LIBRARY_DIRS_ABS}")
```
- Remove invalid dynamic cast in bullet

Fix benchmark CI along with minor fixes

---

tesseract_kinematics/core/include/tesseract_kinematics/core/utils.h
tesseract_kinematics/test/kinematics_core_unit.cpp

I just came across these minor improvements of the manipulability calculation when inspecting the code, because a student of mine complained that the eigenvalues are not sorted. Please have a look at the individual commit comments for more details.
For reference: [SelfAdjointEigenSolver](http://eigen.tuxfamily.org/dox/classEigen_1_1SelfAdjointEigenSolver.html)
In principle, the calculation of the inverse expressions is redundant:
https://github.com/tesseract-robotics/tesseract/blob/afe92a7ab892dad856a010d3c7864489d7f3489a/tesseract_kinematics/core/include/tesseract_kinematics/core/utils.h#L355-L360
because eigenvalues(A^-1) = eigenvalues^-1(A). Also, det(A^-1) = 1/det(A).
However, you apply some clipping to the eigenvalues as well...

Improve manipulability calculcation

---

tesseract_urdf/src/convex_mesh.cpp

Convex meshes don't generally save correctly when exporting a URDF because the package path is not included in the file path. This PR updates the convex mesh exporter to match the regular mesh exporter.

Fixed convex mesh export

---

tesseract_common/include/tesseract_common/serialization.h
tesseract_common/include/tesseract_common/serialization_extensions.h
tesseract_common/test/tesseract_common_serialization_unit.cpp
tesseract_srdf/src/srdf_model.cpp

This PR adds a macro for defining extensions for classes which get used when serializing a class if an extension is no provided. This is to better support GUI importing and exporting.

Add tesseract extension macro

---

tesseract_common/src/allowed_collision_matrix.cpp
tesseract_common/src/collision_margin_data.cpp
tesseract_environment/src/commands/change_joint_acceleration_limits_command.cpp
tesseract_environment/src/commands/change_joint_position_limits_command.cpp
tesseract_environment/src/commands/change_joint_velocity_limits_command.cpp
tesseract_environment/src/commands/change_link_collision_enabled_command.cpp
tesseract_environment/src/commands/change_link_origin_command.cpp
tesseract_scene_graph/src/graph.cpp

Including <boost/serialization/library_version_type.hpp> for Boost 1.74. Fixes tesseract-robotics/tesseract#764

Boost 1.74 issue fix

---

.github/workflows/windows_2019.yml

This PR fixes the CI error on Windows by using a newer version of the vcpkg-action.

Use vcpkg-action@v3 in windows_2019.yml workflow

---

README.md

Adds instructions to the readme to install Python. This should help Python users be directed to the correct installation method.

Add Python instructions to README.md

---

.github/workflows/api_docs.yml
.github/workflows/benchmarking.yml

Use the [option to deploy documentation to a separate repository](https://github.com/peaceiris/actions-gh-pages/tree/e5d60a65a4bd200dd1f942fa8e0f677ba7167370#%EF%B8%8F-deploy-to-external-repository-external_repository) in order to remove the large `gh-pages` branch from this repo to improve download time. Addresses #840 and #842

Deploy documentation to separate repository

---

.github/workflows/benchmarking.yml

This PR updates the benchmarking job to push the results to `tesseract_docs` using the `DOCS_DEPLOY_KEY` SSH key that has been added as a Github secret to this repository (with the corresponding public key as a Github deploy key in `tesseract_docs`. 
I made a test job on my own fork that [successfully ran ](https://github.com/marip8/tesseract/actions/runs/4355522900/jobs/7612294903) and added a set of dummy benchmarks to my own fork of `tesseract_docs` [here](https://github.com/marip8/tesseract_docs/tree/d40791e6bed804ac2b8a7c85dc945054b254e8ec/tesseract/dev/bench)
Depends on [merge of existing benchmark data into `tesseract_docs`](https://github.com/tesseract-robotics/tesseract_docs/pull/16)

Benchmark CI Update

---

tesseract_collision/core/include/tesseract_collision/core/types.h
tesseract_collision/core/src/types.cpp

These methods are used by TrajOpt to reduce memory consumption.

Add flattenWrapperResults methods

---

tesseract_collision/core/include/tesseract_collision/core/types.h
tesseract_collision/core/src/types.cpp
tesseract_environment/src/utils.cpp

The goal of this is to improve the terminal output when performing a collision check on a trajectory. In doing this I also created objects for holding collision information from a trajectory that may be useful elsewhere.
Two examples of partial trajectory outputs from running the unit tests:
As compared to the previous output that was much harder to read:
The trajectory collision object provides a function that outputs a std::stringstream in the form of the table seen above. All the columns are adjusted to always be a constant width depending on the longest string in that column, so the output should always look clean, similar to what is done with the trajopt iterations.

Trajectory Collision Logging

---

tesseract_collision/core/src/types.cpp
tesseract_environment/src/utils.cpp

- There were a few places that were missed for adding contacts to the trajectory logger
- The check for debug logging was backwards. Was previously checking if logging was > info (which means warn/error/none) and now is checking if logging is < info which is just debug.
This fix has some time savings for the trajectory checking.

Trajectory logging fixup

---

.github/workflows/ubuntu.yml

Turns out the deletion of all `-dev` libraries from the CI docker image is problematic for downstream builds like `tesseract_planning` and `tesseract_ros2`, since some libraries (like `libtinyxml2-dev`) are only distributed with `-dev` names. In the case below, `trajopt_common` fails because its dependency (`tesseract_common`) can no longer find TinyXML2
```bash
Call Stack (most recent call first):
/usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
/root/tesseract-robotics/tesseract_target_ws/install/tesseract_common/lib/cmake/tesseract_common/FindTinyXML2.cmake:81 (find_package_handle_standard_args)
/usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
/root/tesseract-robotics/tesseract_target_ws/install/tesseract_common …
```

Remove deletion of -dev libraries

---

tesseract_common/cmake/FindTinyXML2.cmake

This greatly speeds up building of all of tesseract, as a lot of time was spent by FindTinyXML2.cmake. (I'll also submit this to https://github.com/ros2/tinyxml2_vendor.)

TinyXML2: do not call find_package() if package has already been found.

---

.github/workflows/clang_format.yml
.github/workflows/cmake_format.yml
.github/workflows/code_quality.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

This PR adds triggers so that branches starting with "dev/" will be built on GitHub actions. This is a convenience when developing on a branch before a pull request is started.

CI build on branches starting with 'dev**'

---

tesseract_kinematics/ikfast/include/tesseract_kinematics/ikfast/ikfast_factory_boilerplate.h

Fixed an issue where the IKFast plugin would fail to parse your `free_joint_state` list if it looked like this:
```
free_joint_states:
- [0.0]
- [-0.1]
- [0.1]
- [-0.2]
- [0.2]
```

Make `free_joint_state` parsing more generalized

---

tesseract_kinematics/kdl/src/kdl_utils.cpp

One of the two implementations of `tesseract_kinematics::parseSceneGraph` appears to have been accidentally deleted in a previous commit (from #928). The header file still had it, but there was no implementation.

Replaced the implementation of `tesseract_kinematics::parseSceneGraph`

---

.github/workflows/benchmarking.yml
.github/workflows/code_quality.yml
.github/workflows/nightly.yml
.github/workflows/ubuntu.yml

Updates CI to use custom version of ICI with that clones shallow with VCS in addition to supporting ROS-independent builds

Updated to version of ICI with VCS shallow cloning

---

.github/workflows/ubuntu.yml

Changes the nominal CI build directory to `/opt`, which, unlike `/root`, is accessible to non-root users. This is valuable for using CI-built docker images in deployment where the docker containers are run with non-root users to support graphics

Changed CI base directory to `/opt`

---

.github/workflows/ubuntu.yml

I am unable to hack ICI to build the repo outside of `/root` and copy the install artifacts to a persistent directory in the Docker image in a way that doesn't refer to the temporary location in which it was built. This reverts commit a74c9efe968ad4b906d5b6e898c9fb476d141388.

Revert "Changed CI base directory to /opt"

---

.clang-tidy
tesseract_collision/vhacd/src/convex_decomposition_vhacd.cpp

- Fixes rounding errors in VHACD progress logging (went up to 101%)
- Fixes some clang-tidy suggestions
- Remove deprecated AnalyzeTemporaryDtors

Logging fix

---

.github/workflows/mac.yml
.github/workflows/windows.yml

Update to v6 of vcpkg-action. v6 optionally uses the new built-in GitHub caching for vcpkg to provide more accurate caching.

Update to vcpkg-action@v6 and use vcpkg-binarycache

---

tesseract_kinematics/kdl/src/kdl_utils.cpp

Remove ineffective frame.Identity() call

---

tesseract_common/src/types.cpp

Faster pair hash for ACM

---

tesseract_common/cmake/tesseract_macros.cmake

Replace [deprecated exec_program](https://cmake.org/cmake/help/v3.0/command/exec_program.html) command by [execute_process](https://cmake.org/cmake/help/v3.0/command/execute_process.html).

Fix deprecated exec_program command

---

tesseract_collision/bullet/src/convex_hull_utils.cpp
tesseract_collision/bullet/src/tesseract_compound_collision_algorithm.cpp

- Apply [bugfix](https://github.com/bulletphysics/bullet3/commit/fce12964139c8073676a50db0201c1460ad3fcad) and [bugfix](https://github.com/bulletphysics/bullet3/commit/a808d7489500935ac6665dcfe930c43a2008566b) from bullet
- Clang-tidy fix

Bullet TesseractCompoundCollisionAlgorithm bugfix

---

tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_fwd_kin_chain.h
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_lma.h
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr.h
tesseract_kinematics/kdl/include/tesseract_kinematics/kdl/kdl_inv_kin_chain_nr_jl.h
tesseract_kinematics/kdl/src/kdl_factories.cpp
tesseract_kinematics/kdl/src/kdl_inv_kin_chain_lma.cpp
tesseract_kinematics/kdl/src/kdl_inv_kin_chain_nr.cpp
tesseract_kinematics/kdl/src/kdl_inv_kin_chain_nr_jl.cpp
tesseract_kinematics/test/kdl_kinematics_unit.cpp
tesseract_kinematics/test/kinematics_factory_unit.cpp

- Add KDL parameters to KDLInvKinChainNR_JL (see #843)
- Some clang_tidy and typo fixes (incl. removing [unnecessary std::move](https://clang.llvm.org/extra/clang-tidy/checks/performance/move-const-arg.html))

Add KDL parameters to KDLInvKinChainNR_JL

---

.github/workflows/windows.yml
tesseract_common/CMakeLists.txt
tesseract_common/cmake/tesseract_common-config.cmake.in
tesseract_common/include/tesseract_common/kinematic_limits.h
tesseract_common/include/tesseract_common/type_erasure.h
tesseract_kinematics/core/src/utils.cpp

Now when you have an invalid cast exception with the type erasure you will get a detailed backtrace like what is shown below.
``` bash
C++ exception with description "TypeErasureBase, tried to cast 'N16tesseract_common10JointStateE' to 'd'
Backtrace:
0# double& tesseract_common::TypeErasureBase<tesseract_common::TypeErasureInterface, tesseract_common::detail_any::AnyInstance>::as<double>() at ~/catkin_ws/tesseract_ws/src/tesseract-1/tesseract_common/include/tesseract_common/type_erasure.h:225
1# TesseractCommonUnit_anyUnit_Test::TestBody() at ~/catkin_ws/tesseract_ws/src/tesseract-1/tesseract_common/test/tesseract_common_unit.cpp:378
2# void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) at …
```

Add backtrace to type erasure casting to quickly identify where the issue location

---

tesseract_environment/src/command.cpp

There are 656 lines of serialization code within tesseract and these two line had the incorrect syntax.

Fix command serialization

---

tesseract_collision/core/include/tesseract_collision/core/types.h
tesseract_collision/core/src/types.cpp

This is to address the problem brought up [here](https://github.com/tesseract-robotics/tesseract_planning/pull/401#issuecomment-2145885476)
The output looks like this:
```
Link Name                      Collisions
-----------------------------------------
robot_link_2                   105
robot_link_3                   95
environment_object1            64
robot_link_4                   61
environment_object2            60
environment_object3            58
environment_object4            28
environment_object5            27
environment_object6            16
environment_object7            6
environment_object8            2
```
This is intended to help debug if the user realizes that the haven't disabled a collision, or give the user a place to look for what might be causing problems

Add ability to briefly summarize trajectory collisions

---

.github/workflows/docker.yml
docker/Dockerfile

Adds changes similar to #1006 to support Docker image build on 24.04

Updated Dockerfile to support 24.04

---

.github/workflows/windows.yml
tesseract_common/src/resource_locator.cpp
tesseract_common/test/resource_locator_unit.cpp
tesseract_common/test/tesseract_common_unit.cpp
tesseract_support/src/tesseract_support_resource_locator.cpp

This enables the use of the latest vcpkg release with boost 1.85 after the serialization failure was fixed in #1034.
Also fixes some deprecated boost::filesystem functions.

Use latest vcpkg release for GitHub Action

---

.github/workflows/mac.yml
tesseract_common/cmake/tesseract_macros.cmake
tesseract_common/include/tesseract_common/yaml_utils.h
tesseract_environment/src/environment.cpp

Mac OS reports "Clang" as "AppleClang" and wasn't being detected. This PR fixes the compiler detection and a few compiler sign comparison warnings.

Fix clang detection on Mac OS

---

tesseract_common/include/tesseract_common/type_erasure.h

Include `<stdexcept>` in type_erasure.h to fix MSVC 2019 compiler error in tesseract_command_language.

Include stdexcept in type_erasure.h

---

.github/workflows/mac.yml
tesseract_collision/bullet/src/bullet_utils.cpp
tesseract_collision/fcl/include/tesseract_collision/fcl/fcl_collision_object_wrapper.h
tesseract_collision/fcl/include/tesseract_collision/fcl/fcl_utils.h
tesseract_collision/fcl/src/fcl_collision_object_wrapper.cpp
tesseract_collision/fcl/src/fcl_utils.cpp
tesseract_collision/test_suite/include/tesseract_collision/test_suite/collision_compound_mesh_sphere_unit.hpp

Fix #1053 
@rjoomen After looking through the code I went a slight different route to solve another issue with get the correct shape index. Do you mind testing this?

Fix use of compound mesh in FCL

---

tesseract_collision/core/include/tesseract_collision/core/types.h

This can be useful for motion planning debugging.

Get a brief string summary of a contact map

---

tesseract_environment/include/tesseract_environment/environment.h
tesseract_environment/src/environment.cpp

This change improves performance in motion planning. Both the JointGroup and KinematicGroup only have const methods so to avoid making duplicate copies they can all share the same object.

Change environment getJointGroup and getKinematicGroup to return shared pointers

---

tesseract_collision/core/CMakeLists.txt

Added to fix cpack debian building.

Add 'COMPONENT core' to collision header install

---

tesseract_collision/core/include/tesseract_collision/core/contact_managers_plugin_factory.h
tesseract_collision/core/src/contact_managers_plugin_factory.cpp
tesseract_collision/test/contact_managers_factory_static_unit.cpp
tesseract_collision/test/contact_managers_factory_unit.cpp
tesseract_common/include/tesseract_common/yaml_utils.h
tesseract_common/src/yaml_utils.cpp
tesseract_common/test/tesseract_common_unit.cpp
tesseract_kinematics/core/include/tesseract_kinematics/core/kinematics_plugin_factory.h
tesseract_kinematics/core/src/kinematics_plugin_factory.cpp
tesseract_kinematics/test/kinematics_factory_unit.cpp
tesseract_srdf/src/configs.cpp
tesseract_srdf/test/tesseract_srdf_unit.cpp

This leverages new utils for loading yaml content that supports the `!include` directive.

Leverage tesseract_common loadYamlFile and loadYamlString

---

tesseract_common/include/tesseract_common/resource_locator.h
tesseract_common/src/resource_locator.cpp

This PR adds API functions to GeneralResourceLocator to add paths to the locator using a constructor overload or the new `addPath()` function.

Add path API functions to GeneralResourceLocator

---

tesseract_environment/include/tesseract_environment/environment.h
tesseract_environment/src/environment.cpp
tesseract_environment/test/benchmarks/check_trajectory_benchmarks.cpp
tesseract_environment/test/benchmarks/environment_clone_benchmarks.cpp
tesseract_environment/test/benchmarks/kinematics_benchmarks.cpp
tesseract_kinematics/core/src/joint_group.cpp
tesseract_scene_graph/include/tesseract_scene_graph/kdl_parser.h
tesseract_scene_graph/include/tesseract_scene_graph/scene_state.h
tesseract_scene_graph/src/kdl_parser.cpp
tesseract_scene_graph/src/scene_state.cpp
tesseract_scene_graph/test/tesseract_scene_graph_unit.cpp
tesseract_state_solver/include/tesseract_state_solver/kdl/kdl_state_solver.h
tesseract_state_solver/include/tesseract_state_solver/ofkt/ofkt_nodes.h
tesseract_state_solver/include/tesseract_state_solver/ofkt/ofkt_state_solver.h
tesseract_state_solver/include/tesseract_state_solver/state_solver.h
tesseract_state_solver/src/kdl_state_solver.cpp
tesseract_state_solver/src/ofkt_nodes.cpp
tesseract_state_solver/src/ofkt_state_solver.cpp
tesseract_state_solver/test/state_solver_test_suite.h
tesseract_state_solver/test/tesseract_state_solver_ofkt_unit.cpp

Master Branch:
``` bash
Running ./tesseract_environment_kinematics
Run on (16 X 4600 MHz CPU s)
CPU Caches:
L1 Data 48K (x8)
L1 Instruction 32K (x8)
L2 Unified 1280K (x8)
L3 Unified 24576K (x1)
Load Average: 0.26, 1.58, 1.59
-----------------------------------------------------------------------------------------------------
Benchmark                                                           Time             CPU   Iterations
-----------------------------------------------------------------------------------------------------
BM_GET_STATE_JOINT_NAMES_JOINT_VALUES_SS/real_time               6.76 us         6.76 us       104520
BM_SET_AND_GET_STATE_JOINT_NAMES_JOINT_VALUES_SS/real_time       6.35 us         6.35 us       109127
BM_GET_JACOBIAN_JOINT_NAMES_JOINT_VALUES_SS/real_time …
```

Add floating joint support

---

tesseract_collision/bullet/CMakeLists.txt
tesseract_collision/bullet/include/tesseract_collision/bullet/bullet_collision_shape_cache.h
tesseract_collision/bullet/include/tesseract_collision/bullet/bullet_utils.h
tesseract_collision/bullet/src/bullet_collision_shape_cache.cpp
tesseract_collision/bullet/src/bullet_utils.cpp
tesseract_collision/fcl/CMakeLists.txt
tesseract_collision/fcl/include/tesseract_collision/fcl/fcl_collision_geometry_cache.h
tesseract_collision/fcl/src/fcl_collision_geometry_cache.cpp
tesseract_collision/fcl/src/fcl_utils.cpp
tesseract_collision/test_suite/include/tesseract_collision/test_suite/collision_box_box_unit.hpp

This avoid creating duplicate underlying collision shapes for bullet and fcl when provided the collision geometry shared pointer. This speeds up things like leveraging the environment command for adding trajectory as a collision link.

Add collision shape caching based on tesseract_geometry::Geometry object

---

tesseract_collision/bullet/src/bullet_utils.cpp
tesseract_collision/fcl/src/fcl_utils.cpp

There seems to be an issue with reusing collision shapes in some cases. It odd that this causes issues but multiple clones do not which seem to share collision shapes.

Disable collision shape caching in bullet and fcl

---

tesseract_collision/core/src/contact_managers_plugin_factory.cpp
tesseract_collision/test/contact_managers_factory_unit.cpp
tesseract_common/include/tesseract_common/yaml_utils.h
tesseract_common/src/yaml_utils.cpp
tesseract_kinematics/core/src/kinematics_plugin_factory.cpp
tesseract_srdf/src/configs.cpp

There was performance issues with the processYamlIncludeDirective utility function for process yaml include directive described [here](https://github.com/tesseract-robotics/tesseract_planning/issues/631). The issues was related to it was make a lot of copies and temporary variable leading to performance issues. The utility function was switched to perform an in place modification to avoid the copying and temporary variables. Running @marrts tests showed significant improvement in performance. The increase time with subseqent calls to this function providing the same root yaml node that @marrts was seeing with the original version was not a bug but dues to the copying leading to memory fragmentation. Improved performance was seen if the root yaml node was copied for each call to this …

Improve processYamlIncludeDirective peformance

---

tesseract_collision/core/include/tesseract_collision/core/types.h
tesseract_collision/core/src/types.cpp
tesseract_collision/test/collision_core_unit.cpp

Print a condensed summary of contacts over a trajectory. Report the first contact observed at each step, regardless of if multiple contacts and substeps with contacts are present. Useful for quick, but informative, debugging.
Of the form
```
Step 14.4: [link_a, link_b]->0.001
```
This means link_a and link_b colliding 40% of the way from step 14 to step 15 and the contact distance observed was 0.001

Implement a condensed summary for ContactTrajectoryResults
